### ISSUE TITLE
Window resize handles are only on the bottom right

### ISSUE THREAD

**Issue by lf-** [kraxarn/spotify-qt#104]
### System information

```
ABI: x86_64-little_endian-lp64
App version: v3.6-dev (678c408d) - lib v0.4
Current desktop: KDE
D-Bus support: Yes
Device: tail-bot (Computer)
Kernel: linux 5.11.16-arch1-1
Product: Arch Linux
Qt version: 5.15.2
```

### Detailed information
There are no handles to resize the window except on the bottom right corner. If I mouse over the right side, bottom side, left side, other corners, etc, the cursor does not change, and the window cannot be grabbed to change its size.

### What should happen?
I would like to be able to resize the window like a normal window by dragging from any side or corner.

**Comment by kraxarn** [comment]
It's just not implemented yet :p
