### ISSUE TITLE
Feature request: Keyboard's player control keys

### ISSUE THREAD

**Issue by uninhm** [kraxarn/spotify-qt#106]
Play/pause, stop, previous and next.

**Comment by kraxarn** [comment]
MPRIS support is already implemented, though, it's buggy under KDE (#4) and unavailable on anything that isn't Linux.
It's mostly because I only know how it works under Linux, but pull requests are very welcome for other operating systems.

**Comment by uninhm** [comment]
I tried in GNOME and it didn't work

**Comment by kraxarn** [comment]
Did you try enabling "Media controller" under "Settings > Application > General"?

**Comment by uninhm** [comment]
> Did you try enabling "Media controller" under "Settings > Application > General"?

Nope, and I removed Gnome :sweat_smile:

**Comment by kraxarn** [comment]
I'm closing this as it's a known issue and a duplicate anyway :relaxed:

**Comment by uninhm** [comment]
There isn't such setting

I came back to GNOME :laughing:

**Comment by kraxarn** [comment]
Unfortunately, this is probably still an issue. Fortunately though, it's something I'm currently working on improving, so hopefully it will be fixed soon. You can still try enabling the media controller option for some basic support though.

**Comment by uninhm** [comment]
But I didn't find the setting you said, I don't know how to enable that "media controller"
![image](https://user-images.githubusercontent.com/62044675/130500523-a8a4558e-f0bd-44ce-acee-22f527a54d2e.png)

**Comment by kraxarn** [comment]
It's in spotify-qt, if you click the menu icon in the top left, click Settings and go to "Application > General" and enable "Media controller" if it's there. If it's not, depending on how you installed it, it's likely you're missing the Qt D-Bus package.

**Comment by uninhm** [comment]
Oh, I thought it was in GNOME Settings > Applications :laughing: 
Anyway, activating the media controller gets the play/pause button working for play but not for pause.
