### ISSUE TITLE
Premium requires

### ISSUE THREAD

**Issue by michaldybczak** [kraxarn/spotify-qt#11]
You failed to mention that premium account is required,. Without it, your app just won't work. This should be not only here on the very beginning of the description, but also on the authentication window.

This leads us to the wild goose chase to install app, then create the spotify app, get ID and secret number to find out in the end, this won't work :(.

**Comment by kraxarn** [comment]
A premium account shouldn't be required. I haven't tried it, but it should still work with a free account as well. What issues are you having?

**Comment by michaldybczak** [comment]
The best way is to show you -> see the info on the bottom of the window? It shows up when I hit the play button.

![Screenshot_20200502_211346](https://user-images.githubusercontent.com/10132958/80873565-de9eaa00-8cb9-11ea-8825-db6c225c74ea.png)

**Comment by kraxarn** [comment]
That's weird. The quick start guide refers to [both type of accounts working](https://developer.spotify.com/documentation/web-api/quick-start), but I guess not. I'll update the readme in that case.

**Comment by michaldybczak** [comment]
Maybe I did something wrong, but I assume, since you didn't know about it, you have a premium account. Get a second info from someone without premium to see if it produces the same result.
However, it sounds reasonable that Spotify reserved this kind of feature for premium users. Exactly the same is for other apps like Clementine where you could connect to Spotify but it works for premium users only.

**Comment by michaldybczak** [comment]
> The quick start guide refers to [both type of accounts working](https://developer.spotify.com/documentation/web-api/quick-start), but I guess not.

Ah, I get it now. This is indeed confusing and... tricky. The guide does mention premium and free Spotify account and that check, because I do have free account. I was able to use this free account to sign in into developer account. This check out too. The only caveat here is, YOU NEED TO BE PREMIUM USER TO STREAM SPOTIFY MUSIC VIA NON-SPOTIFY APP. This is something entirely different and not mentioned in the guide, which covers the developer part where free account is enough, but on a receiving end, premium one must be used.

All clear now.

**Comment by kraxarn** [comment]
[They do list it](https://developer.spotify.com/documentation/web-api/reference/player/start-a-users-playback) with possible errors in the documentation when controlling playback. This could also be used to control the official client, but at that point it's probably not even worth it.

**Comment by silvtal** [comment]
I agree that this should be stated somewhere at the start of the installation. I found the app at the ubuntu software app and lost time setting everything up for nothing.

**Comment by kraxarn** [comment]
Clarified this a bit more in the readme (f139eb92237abee3af7426d67d039aac0b049d06) and updated the description on the snap page to also more clearly mention it.
