### ISSUE TITLE
Any way to view podcasts on here?

### ISSUE THREAD

**Issue by onkoe** [kraxarn/spotify-qt#110]
I usually don't use Spotify, but I would like to watch a few recent episodes of the Joe Rogan Experience. Searching for that results in an empty search box. Is there any way to access this podcast from this (very nice) client? Thanks!

**Comment by kraxarn** [comment]
From what I can tell, the Web API has support for podcasts, so support for it can be added. I'll look into it and hopefully add support for it in a future release. 
Thanks for the kind words :relaxed:

**Comment by kraxarn** [comment]
Some things to note about podcast support:
* I didn't test it, but I don't think librespot/spotifyd has support for podcasts, as they are usually in the mp3 format, which I don't think is supported. I tried it with librespot-java though,  which seems to work fine.
* Playback status doesn't seem to be properly reported from the API. This means that spotify-qt will show as if nothing is playing while listening to an episode.
