### ISSUE TITLE
`[err ] me/player/devices failed` No devices in device list

### ISSUE THREAD

**Issue by shreyasminocha** [kraxarn/spotify-qt#111]
After a wake from suspend, spotify-qt doesn't list any devices in the device menu and is unable to play tracks until it's restarted. Not a duplicate of #26.

I'm not sure if this is related to https://github.com/Spotifyd/spotifyd/issues/706. Earlier (with the same version of spotify-qt) I was able to fix that by restarting spotifyd from within spotify-qt settings, but that doesn't seem to fix this.

### Steps to reproduce

- Start spotify-qt
- Suspend device
- Wake
- Confirm that you're re-connected to the internet
- Confirm that a spotifyd process is running

### System information

```
ABI: x86_64-little_endian-lp64
App version: v3.6
Current desktop: KDE
D-Bus support: Yes
Kernel: linux 5.12.14-arch1-1
Product: Arch Linux
Qt version: 5.15.2
```

### Logs

```
"No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/ActiveConnection/47"
"No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/ActiveConnection/46"
…
"No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/ActiveConnection/47"
"No such interface “org.freedesktop.DBus.Properties” on object at path /org/freedesktop/NetworkManager/ActiveConnection/46"
[12:44:10 PM IST] [err ] me/player/devices failed: [json.exception.type_error.304] cannot use at() with null
[12:44:20 PM IST] [err ] me/player/devices failed: [json.exception.type_error.304] cannot use at() with null
```

**Comment by kraxarn** [comment]
Adding detection for when the client crashes, or loses connectivity, and automatically restarting it, would be good, but if restarting the client from the spotify-qt settings doesn't work, it might not help, and be some other issue with spotify-qt.
Does Spotify > Logs show anything of interest?

**Comment by shreyasminocha** [comment]
> Does "Spotify > Logs" show anything of interest?

```
[19:26:42] Caught panic with message: called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: "https://api.spotify.com/v1/me/player", source: TimedOut }
```

As for "Application > Logs", that adds another `[err ] me/player/devices failed: [json.exception.type_error.304] cannot use at() with null` each time I hover on "Devices".

Upon restarting the client (which was started from spotify-qt) from within Settings, "Spotify > Logs" just shows a successful Connecting-Authenticated-Country, but hovering over the Devices menu continues to add the `[err ] me/player/devices failed` lines to the application log.

**Comment by kraxarn** [comment]
Closing as it's probably not an issue with spotify-qt.
