### ISSUE TITLE
Cant adjust the volume with the slider

### ISSUE THREAD

**Issue by Mettfisto** [kraxarn/spotify-qt#112]
## System information

-  Operating System: Manjaro Linux
-  KDE Plasma Version: 5.21.5
-  KDE Frameworks Version: 5.82.0
-  Qt Version: 5.15.2
-  Kernel Version: 5.10.42-1-MANJARO
-  OS Type: 64-bit
-  Graphics Platform: X11
-  Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
-  Memory: 15,6 GiB of RAM
-  Graphics Processor: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2

### What happens?

Cant adjust the volume, the volume slider allways jumps back and if its stays nothing changes, i am using alsa as backend.
#### spotifyd Config

```
[global]
username = *****
password = *****
# password_cmd = "command_that_writes_password_to_stdout"
use_keyring = false
use_mpris = true
backend = "alsa"
device = "hw:1" 
control = "hw:1"
# on_song_change_hook = "command_to_run_on_playback_events"
mixer = "PCM"
volume_controller = "alsa" 
device_name = "spotifyd"
bitrate = 320
cache_path = "/home/user/.spotifyd/cache"
no_audio_cache = true
initial_volume = "90"
volume_normalisation = true
normalisation_pregain = -10
zeroconf_port = 1234
# proxy = "http://proxy.example.org:8080"
device_type = "speaker"
```

###  What should happen?

I should be able to adjust the volume with the slider

**Comment by kraxarn** [comment]
Do you have "Settings > Application > PulseAudio volume control" enabled?
Is anything weird shown in "Settings > Spotify > Logs"?
What version of the application are you using?

**Comment by Mettfisto** [comment]
I dont have the option in spotify-qt under applications to enable pulse audio volume control,
Under application i got 
- General 
  - Refresh Interval
  - Queue limit
  - Media Controller
  - Show whats new on start
- Logs

I am using
- spotify-qt 3.6
- spotifyd 0.3.2-1

Under Spotify Logs, logs dont show anything
Under Application Logs, logs just show 
```
[12:14:11] [info] Last refresh was less than an hour ago, not refreshing access token
```

**Comment by kraxarn** [comment]
Hopefully the improvements made are enough to make it feel better. There are still some issues where if you adjust the volume, but the player status updates before the volume properly updates, it jumps back to the previous volume, before jumping back to the new one set. It's just a visual issue, and it should work much better now, so hopefully it's enough.
