### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by zielony12** [kraxarn/spotify-qt#116]
### System information
OS: FreeBSD 13.0-RELEASE

### Detailed information
Cannot authenticate

### What happens?
At welcome message i have entered my new app id and token but it wont log in me. It opens new tab in my web browser and i have a message: "INVALID_CLIENT: Invalid redirect URI"

### What should happen?
It should log me in

**Comment by kraxarn** [comment]
Duplicate of #3?
(enter the specified URL from the app in “Redirect URIs” and not “Website”)
