### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by hellproducts** [kraxarn/spotify-qt#12]
After release 1.7, the spotifyd daemon does not start along with spotify-qt, even though I'm still being prompted for the password.
Starting spotifyd by hand and then connecting spotify-qt to that device works fine.

**Comment by kraxarn** [comment]
Should probably have tested a bit more with it before releasing an update. I probably know what's causing it, but make sure you compiled spotifyd with pulseaudio support anyway. 1.8 should be released later today with a fix.

**Comment by hellproducts** [comment]
It's compiled with pulseaudio, yes.
I'll wait for the update and see how it works. I really like spotifyd starting with spotify-qt because otherwise I either need to start it by hand or using a service ('cause I'm lazy).
Also, thank you for the very quick response!
