### ISSUE TITLE
Client-Side Decorations assume window controls on the right

### ISSUE THREAD

**Issue by falkTX** [kraxarn/spotify-qt#120]
### System information
```
App version:     | v3.7-dev (75b1cd1a) - lib v0.5
Current desktop: | KDE
D-Bus support:   | Yes
KCrash support:  | No
Kernel:          | linux 5.11.0-27-generic
Product:         | Ubuntu 20.04.3 LTS
Qt version:      | 5.15.3
Window system:   | X11
```

### Detailed information
spotify-qt assumes my window decorations have controls on the right side, which is not the case.
so the default CSD controls do not match the desktop.

### What happens?
The wrong behaviour is easily seen in the screenshot below

![Screenshot_20210903_141833](https://user-images.githubusercontent.com/1334853/132011523-af0c3027-afe2-4d4d-8b33-021430056045.png)

### What should happen?
The window controls should be on the left for systems that are setup that way.
Since spotify-qt supports macOS, this should already be supported no?

Seems like a matter of finding the user setting for this.

**Comment by kraxarn** [comment]
Completely forgot about that xd
Afaik, because the application has no direct access to the window manager, there's no easy way to tell which side the titlebar buttons are on. The best solution for now is probably to add an option to mirror the buttons and default it to enabled on macOS.
