### ISSUE TITLE
Minimize to system tray instead of taskbar

### ISSUE THREAD

**Issue by Katzenwerfer** [kraxarn/spotify-qt#124]
This isn't much of an issue, but would be a nice QOL change.
It kinda helps keeping the taskbar organized and since there is already an option to show a system tray icon I don't see the point on having both at the same time (taskbar and tray)

**Comment by kraxarn** [comment]
You can minimize the application to tray by clicking the tray icon, but an option to also minimize to tray when minimizing/closing the application could be nice.

**Comment by kraxarn** [comment]
This was fixed in #151 (v3.9).
