### ISSUE TITLE
App reads W11 as W10 version 2009 at system info

### ISSUE THREAD

**Issue by CerealBowl** [kraxarn/spotify-qt#129]
### Detailed information

https://prnt.sc/1txzpcc - should say W11 there or something
### What happens?

1. install w11 (then uninstall it completely its the worst system i have ever worked on)
2. install the client
3. go to settings, system information
4. see win 10 version 2009 instead of the w11 latest compilation number etc etc
### What should happen?

it should show w11

**Comment by kraxarn** [comment]
From what I've heard it's even shown in the system itself, so I don't think it's something that I can do about it.
Either way, that information is fetched directly from Qt, so if it's an actual bug, it's a bug in Qt and not within spotify-qt itself.
