### ISSUE TITLE
Unable to move spotify-qt window under Wayland

### ISSUE THREAD

**Issue by 31j** [kraxarn/spotify-qt#134]
### System information

ABI: x86_64-little_endian-lp64
App version: v3.7-dev (c8394e55) - lib v0.5
Current desktop: KDE
D-Bus support: Yes
Device: Spotifyd@Gaia (Speaker)
KCrash support: No
Kernel: linux 5.14.15-300.fc35.x86_64
Product: Fedora Linux 35.20211104.0 (Kinoite)
Qt version: 5.15.2
Window system: Wayland

### Detailed information

Unable to drag application without enabling system titlebar OR re-building without `qt5-qtwayland-devel` (and using xwayland)
### What happens?

- Build spotifyd (my build environment is Fedora 35 in toolbox (podman))
- Open & configure
- Cannot move the window

### What should happen?

One should be able to move the window

**Comment by kraxarn** [comment]
Seems to be a bug in KWin, as I'm unable to reproduce the issue under GNOME with Wayland. I do get some really weird mouse positions under KWin though, causing menus and such to break as well.
