### ISSUE TITLE
Program segfaults when you attempt to shuffle play a playlist using the context menu

### ISSUE THREAD

**Issue by JamiKettunen** [kraxarn/spotify-qt#14]
Steps to reproduce:
1. Open `spotify-qt`
2. Search for something
3. Go to the `Playlists` tab
4. Right-click on a playlist and choose `Shuffle play`

Expected behavior:
* Songs from the chosen playlist start to play in a shuffled order without the program crashing.

Observed behavior:
* The program segfaults, the GUI dies after around a second of waiting and nothing starts to play.

System info:
* Arch Linux
* Everything is fully up-to-date as of reporting this issue (spotifyd 0.2.2.24, soptify-qt 2.1, qt 5.15, ...)

Full crash log from `journalctl`:
* [crash-journal.log](https://github.com/kraxarn/spotify-qt/files/4758379/crash-journal.log)

**Comment by kraxarn** [comment]
Was actually something completely different, it didn't find the playlist for the context menu correctly at all, oops.
