### ISSUE TITLE
Spotifyd unrecognized options

### ISSUE THREAD

**Issue by AozoraDev** [kraxarn/spotify-qt#142]
### System information
Away from laptop rn so ¯\_(ツ)_/¯

### Detailed information
Just adding `/snap/spotifyd/current/bin/spotifyd` (cmiiw) to the path then it gives output like `unrecognized options: version`. Then i go to the logs and it gives output like `unrecognized options: device-name`.
(Oh, spotify-qt AUR btw.)

### What happens?
- Add `/snap/spotifyd/current/bin/spotifyd` to the spotify path.
- Save and then exit
- Open the app
- Insert password
- Nothings happen lol

### What should happen?
Idk, no `device not found` error anymore?

**Comment by AozoraDev** [comment]
And of course! spotifyd from snap already installed.

**Comment by AozoraDev** [comment]
Oh nvm. Just following #70 and things get fixed.

**Comment by kraxarn** [comment]
Yeah, it should probably be better documented on the wiki or something, I agree.
Also, any reason you chose to install spotifyd from snap instead of from the official repositories? Assuming you're using Arch, as you installed spotify-qt from AUR.

**Comment by AozoraDev** [comment]
I just followed the solution I found in Issue.
