### ISSUE TITLE
Not all followed artists are visible

### ISSUE THREAD

**Issue by petr-nehez** [kraxarn/spotify-qt#145]
### System information
![image](https://user-images.githubusercontent.com/1265990/148907693-6e983067-b850-4848-8fa8-5c3996a81a48.png)
RHEL 8.5

### Detailed information
I follow many artists but I do see only limited set of those artists under "Followed Artists".

### What happens?
![image](https://user-images.githubusercontent.com/1265990/148908469-ab590215-7569-414f-9a68-922991052526.png)

**Comment by petr-nehez** [comment]
Thanks! :+1:

**Comment by kraxarn** [comment]
Thank you for reporting the issue :relaxed:
