### ISSUE TITLE
Windows builds are incompatible with Qt 6.2

### ISSUE THREAD

**Issue by a-singer** [kraxarn/spotify-qt#146]
Hello,

I don't seem to be able to get 3.8 to launch where 3.7 worked on both machines I tried it with. On my Windows 7 machine, it says

The procedure entry point CreateEventW could not be located in the dynamic link library api-ms-win-core-synch-l1-2-0.dll. 

On a Windows 10 machine it says

Connection failed. Unexpected Response: No Response.

I apologise if I should be putting these out as two separate issues but I'm thinking I may have done something wrong with the download, 3.7 works well with both these machines. What I did was to unzip the file into its own folder, and I think, though it's been a while, that this is the same thing I did in 3.7.

Thanks,

**Comment by kraxarn** [comment]
Thanks a lot for bringing my attention to it! Just tried it out in a Windows VM, and I'm able to reproduce the issue. Very odd. I've removed the Windows download for it while looking more into it.

**Comment by kraxarn** [comment]
Turns out there was a change in how Qt 6.2 handles SSL, which made all network requests fail. For now, I've modified the build script to use Qt 6.1 instead, which seems to work fine. I also uploaded the new build to the release page, so please download and try that version instead.

I'll leave this issue open for now until the Windows builds work with Qt 6.2.

**Comment by a-singer** [comment]
Hi,


     Though I know you'd like to get this working with 6.2, I thought I 
would mention that, on my machine, 3.8.1 works well. That is, the 
problem is fixed here though only by going back to 6.1. Thanks very much 
for your fast work on this and for what is an excellent release.

**Comment by kraxarn** [comment]
I've had plans to switch out the Windows building system to the official Qt binaries for a while, and just doing so made 6.2 work perfectly. I won't update the 3.8 build with Qt 6.2, but 3.9 will include Windows builds with the new build system, including Qt 6.2.
