### ISSUE TITLE
Crashes after choosing Spotify Connect speaker

### ISSUE THREAD

**Issue by philippgerard** [kraxarn/spotify-qt#15]
Using latest version from AUR as of writing (2.3.1, build date 23.6.20). The first launch works fine. After choosing a speaker from my Spotify Connect list in the devices list, the app crashes. All subsequent launches crash after showing the window for half a second until I restart the system (Manjaro unstable running 5.7). The system has a running daemon of spotifyd and is spotify-qt is configured to use it. Can I provide more information?

`Jun 23 09:24:34 philipp-blade-manjaro systemd-coredump[27916]: Process 27891 (spotify-qt) of user 1000 dumped core.
                                                               
                                                               Stack trace of thread 27891:
                                                               #0  0x00007f85c72bed41 _ZN15QSystemTrayIcon7setIconERK5QIcon (libQt5Widgets.so.5 + 0x4d3d41)
                                                               #1  0x0000556516700806 n/a (spotify-qt + 0x56806)
                                                               #2  0x00005565166dc294 n/a (spotify-qt + 0x32294)
                                                               #3  0x00007f85c64b0906 n/a (libQt5Core.so.5 + 0x2e9906)
                                                               #4  0x00005565166c8896 n/a (spotify-qt + 0x1e896)
                                                               #5  0x00005565167121fc n/a (spotify-qt + 0x681fc)
                                                               #6  0x00007f85c64b0906 n/a (libQt5Core.so.5 + 0x2e9906)
                                                               #7  0x00005565166c8843 n/a (spotify-qt + 0x1e843)
                                                               #8  0x00005565167120f6 n/a (spotify-qt + 0x680f6)
                                                               #9  0x00007f85c64b0906 n/a (libQt5Core.so.5 + 0x2e9906)
                                                               #10 0x00007f85c754cea3 _ZN21QNetworkAccessManager8finishedEP13QNetworkReply (libQt5Network.so.5 + 0x45ea3)
                                                               #11 0x00007f85c754e258 n/a (libQt5Network.so.5 + 0x47258)
                                                               #12 0x00007f85c64b0906 n/a (libQt5Core.so.5 + 0x2e9906)
                                                               #13 0x00007f85c75abd85 n/a (libQt5Network.so.5 + 0xa4d85)
                                                               #14 0x00007f85c64a60b2 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x2df0b2)
                                                               #15 0x00007f85c6f47702 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15c702)
                                                               #16 0x00007f85c647969a _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2b269a)
                                                               #17 0x00007f85c647c183 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x2b5183)
                                                               #18 0x00007f85c64d2bd4 n/a (libQt5Core.so.5 + 0x30bbd4)
                                                               #19 0x00007f85c4eec43c g_main_context_dispatch (libglib-2.0.so.0 + 0x5243c)
                                                               #20 0x00007f85c4f39fa9 n/a (libglib-2.0.so.0 + 0x9ffa9)
                                                               #21 0x00007f85c4eeb221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                                                               #22 0x00007f85c64d2211 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30b211)
                                                               #23 0x00007f85c647801c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b101c)
                                                               #24 0x00007f85c64804a4 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2b94a4)
                                                               #25 0x00005565166c8333 n/a (spotify-qt + 0x1e333)
                                                               #26 0x00007f85c5e2e002 __libc_start_main (libc.so.6 + 0x27002)
                                                               #27 0x00005565166c84ae n/a (spotify-qt + 0x1e4ae)
                                                               
                                                               Stack trace of thread 27895:
                                                               #0  0x00007f85c5efc05f __poll (libc.so.6 + 0xf505f)
                                                               #1  0x00007f85c4f39f38 n/a (libglib-2.0.so.0 + 0x9ff38)
                                                               #2  0x00007f85c4eeb221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                                                               #3  0x00007f85c64d2211 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30b211)
                                                               #4  0x00007f85c647801c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b101c)
                                                               #5  0x00007f85c6293c32 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccc32)
                                                               #6  0x00007f85c6294e0f n/a (libQt5Core.so.5 + 0xcde0f)
                                                               #7  0x00007f85c5dee422 start_thread (libpthread.so.0 + 0x9422)
                                                               #8  0x00007f85c5f06bf3 __clone (libc.so.6 + 0xffbf3)
                                                               
                                                               Stack trace of thread 27913:
                                                               #0  0x00007f85c5df4e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                                                               #1  0x00007f85b15583bc n/a (iris_dri.so + 0x4ae3bc)
                                                               #2  0x00007f85b1556db8 n/a (iris_dri.so + 0x4acdb8)
                                                               #3  0x00007f85c5dee422 start_thread (libpthread.so.0 + 0x9422)
                                                               #4  0x00007f85c5f06bf3 __clone (libc.so.6 + 0xffbf3)
                                                               
                                                               Stack trace of thread 27894:
                                                               #0  0x00007f85c5efc05f __poll (libc.so.6 + 0xf505f)
                                                               #1  0x00007f85c4f39f38 n/a (libglib-2.0.so.0 + 0x9ff38)
                                                               #2  0x00007f85c4eeb221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                                                               #3  0x00007f85c64d2211 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30b211)
                                                               #4  0x00007f85c647801c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b101c)
                                                               #5  0x00007f85c6293c32 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccc32)
                                                               #6  0x00007f85c7498098 n/a (libQt5DBus.so.5 + 0x17098)
                                                               #7  0x00007f85c6294e0f n/a (libQt5Core.so.5 + 0xcde0f)
                                                               #8  0x00007f85c5dee422 start_thread (libpthread.so.0 + 0x9422)
                                                               #9  0x00007f85c5f06bf3 __clone (libc.so.6 + 0xffbf3)
                                                               
                                                               Stack trace of thread 27910:
                                                               #0  0x00007f85c5df4e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                                                               #1  0x00007f85b15583bc n/a (iris_dri.so + 0x4ae3bc)
                                                               #2  0x00007f85b1556db8 n/a (iris_dri.so + 0x4acdb8)
                                                               #3  0x00007f85c5dee422 start_thread (libpthread.so.0 + 0x9422)
                                                               #4  0x00007f85c5f06bf3 __clone (libc.so.6 + 0xffbf3)
                                                               
                                                               Stack trace of thread 27896:
                                                               #0  0x00007f85c5df5158 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0x10158)
                                                               #1  0x00007f85c629ace8 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd3ce8)
                                                               #2  0x00007f85c6298fd4 n/a (libQt5Core.so.5 + 0xd1fd4)
                                                               #3  0x00007f85c6294e0f n/a (libQt5Core.so.5 + 0xcde0f)
                                                               #4  0x00007f85c5dee422 start_thread (libpthread.so.0 + 0x9422)
                                                               #5  0x00007f85c5f06bf3 __clone (libc.so.6 + 0xffbf3)
                                                               
                                                               Stack trace of thread 27892:
                                                               #0  0x00007f85c5efc05f __poll (libc.so.6 + 0xf505f)
                                                               #1  0x00007f85c2ccd63b n/a (libxcb.so.1 + 0xc63b)
                                                               #2  0x00007f85c2ccf37b xcb_wait_for_event (libxcb.so.1 + 0xe37b)
                                                               #3  0x00007f85c285cc51 n/a (libQt5XcbQpa.so.5 + 0x5dc51)
                                                               #4  0x00007f85c6294e0f n/a (libQt5Core.so.5 + 0xcde0f)
                                                               #5  0x00007f85c5dee422 start_thread (libpthread.so.0 + 0x9422)
                                                               #6  0x00007f85c5f06bf3 __clone (libc.so.6 + 0xffbf3)
                                                               
                                                               Stack trace of thread 27908:
                                                               #0  0x00007f85c5efc05f __poll (libc.so.6 + 0xf505f)
                                                               #1  0x00007f85c4f39f38 n/a (libglib-2.0.so.0 + 0x9ff38)
                                                               #2  0x00007f85c4eeb221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                                                               #3  0x00007f85c64d2211 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30b211)
                                                               #4  0x00007f85c647801c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b101c)
                                                               #5  0x00007f85c6293c32 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccc32)
                                                               #6  0x00007f85c6294e0f n/a (libQt5Core.so.5 + 0xcde0f)
                                                               #7  0x00007f85c5dee422 start_thread (libpthread.so.0 + 0x9422)
                                                               #8  0x00007f85c5f06bf3 __clone (libc.so.6 + 0xffbf3)
                                                               
                                                               Stack trace of thread 27911:
                                                               #0  0x00007f85c5df4e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                                                               #1  0x00007f85b15583bc n/a (iris_dri.so + 0x4ae3bc)
                                                               #2  0x00007f85b1556db8 n/a (iris_dri.so + 0x4acdb8)
                                                               #3  0x00007f85c5dee422 start_thread (libpthread.so.0 + 0x9422)
                                                               #4  0x00007f85c5f06bf3 __clone (libc.so.6 + 0xffbf3)
                                                               
                                                               Stack trace of thread 27912:
                                                               #0  0x00007f85c5df4e32 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xfe32)
                                                               #1  0x00007f85b15583bc n/a (iris_dri.so + 0x4ae3bc)
                                                               #2  0x00007f85b1556db8 n/a (iris_dri.so + 0x4acdb8)
                                                               #3  0x00007f85c5dee422 start_thread (libpthread.so.0 + 0x9422)
                                                               #4  0x00007f85c5f06bf3 __clone (libc.so.6 + 0xffbf3)
                                                               
                                                               Stack trace of thread 27893:
                                                               #0  0x00007f85c5efc05f __poll (libc.so.6 + 0xf505f)
                                                               #1  0x00007f85c4f39f38 n/a (libglib-2.0.so.0 + 0x9ff38)
                                                               #2  0x00007f85c4eeb221 g_main_context_iteration (libglib-2.0.so.0 + 0x51221)
                                                               #3  0x00007f85c64d2211 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30b211)
                                                               #4  0x00007f85c647801c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b101c)
                                                               #5  0x00007f85c6293c32 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccc32)
                                                               #6  0x00007f85c6294e0f n/a (libQt5Core.so.5 + 0xcde0f)
                                                               #7  0x00007f85c5dee422 start_thread (libpthread.so.0 + 0x9422)
                                                               #8  0x00007f85c5f06bf3 __clone (libc.so.6 + 0xffbf3)
`

**Comment by kraxarn** [comment]
Please provide Qt version and desktop environment. Do you have to restart your entire system or is restarting spotifyd enough (for example `killall -9 spotifyd`)?

**Comment by philippgerard** [comment]
Qt version is 5.15.0 and desktop environment is Cinnamon (4.6.0). Killall on spotifyd does not help with the application crashing again when restarted, a full system reboot seems the only thing to fix it.

However, the configuration file fix worked flawlessly! Thank you :-)

I'm happy to provide more logs or input if that can help you resolve the underlying issue, just let me know. And thank you for the great work on spotify-qt!

**Comment by kraxarn** [comment]
You could try compiling from source (or wait for the next release) and enable the option again to see if the issue remains.
Thanks for using spotify-qt and reporting issues 😄
