### ISSUE TITLE
App won't start (Unexpected response: Failed to get client)

### ISSUE THREAD

**Issue by EwanGreen4** [kraxarn/spotify-qt#156]
### System information
Arch Linux on 5.16.11
GCC version 11.2.0
Qt version 5.15.2
spotify-qt version: 3.8 (from AUR)

### Detailed information
Application errors on start, 2 seemingly unrelated errors (seen below):

![image](https://user-images.githubusercontent.com/36348486/158026052-3e0ed2de-f776-4dc4-8096-8c41bcca91c6.png)
`[warn] Failed to initialize crash handler` (via. stderr)
`Unexpected response: Failed to get client` (via. QMessageBox)

### What happens?
spotify-qt is built & run, error following (happens when built from repo directly as well as from AUR)

### What should happen?
App should start and work without fatal errors

**Comment by EwanGreen4** [comment]
Undef'd USE_KCRASH which is the origin of the "Failed to initialize crash handler" error, which should then use the custom one, and it looks like it's not the origin of the issue.

![image](https://user-images.githubusercontent.com/36348486/158027009-3ee89b58-a374-4951-b121-8b3d2374512f.png)

Problem happens here, lands on the `lib::spt::error` catch of `spt::Spotify::tryRefresh()`, and gives me the most vague possible response. I think this is as far as my debugging will take me.

**Comment by EwanGreen4** [comment]
Upon further inspection, it looks like the app is doing all it can, but Spotify is returning the invalid client error. Initially I just did a search for "Failed to get client", but it makes sense now why it didn't show up (`refresh()`). Now my question is why this happens for me but (seemingly) nobody else? I'm unfamiliar with the Spotify API.

**Comment by kraxarn** [comment]
The crash handler is only used if the application would ever crash, and shouldn't be related to the connectivity issue. That error sounds like an authentication error, but you were able to log in and authenticate? You could also try starting the app with `--reset-credentials` and retry authentication to see if that works.

**Comment by EwanGreen4** [comment]
Sorry, I forgot to get back to you on this. It must have been using really old credentials (1yr+) because I haven't used this since about then. I completely forgot about that :stuck_out_tongue:
`--reset-credentials` worked like a dream. I am a little surprised it didn't give an error related to bad auth (as opposed to the vague one it did give). Do you think there's any way to thin it down & make the error more specific, for other people with my issue?

**Comment by kraxarn** [comment]
The error is just what's returned from the API, so I don't think it makes sense to try to be more specific. Having to manually run `--reset--credentials` shouldn't be needed though, it should just do it automatically when the API returns any error.

Improving this is tracked in #64 :relaxed:
