### ISSUE TITLE
[UI] Current played item is sometimes not marked as current played in playlist's tracks panel

### ISSUE THREAD

**Issue by brunetton** [kraxarn/spotify-qt#159]
### System information
Spotify-qt 3.8 - Ubuntu 21.10 (impish)

### Detailed information
I'm often looking for current played item in tracks list (to add it to a playlist typically; or sometimes to remove it from current playlist, that is not featured in official Spotify Android app :-1:) (#157)

Normally to indicate this current track there's a black arrow on the left of current played track in tracks list:
![image](https://user-images.githubusercontent.com/86322/159164257-69e69ed2-250b-43cd-b410-b0b72dabd468.png)

But in some cases this arrow is not present. I'm sorry but I didn't found howto reproduce it :(

**Comment by kraxarn** [comment]
This was hopefully fixed in v3.11
