### ISSUE TITLE
Failing to find a default browser fails silently

### ISSUE THREAD

**Issue by konrad1977** [kraxarn/spotify-qt#16]
Hi I compiled and runned the app on [Haiku](https://www.haiku-os.org). But it fails to start, I dont know if our QT implementation is failing or its because I dont have a premium account. 

I added my client-id and secret from the dashboard. And the spotify-qt compiles without any modifications.

<img width="1440" alt="Skärmavbild 2020-07-02 kl  10 07 14" src="https://user-images.githubusercontent.com/4384932/86333380-17241b00-bc4c-11ea-9577-b0917e3ccac2.png">

**Comment by kraxarn** [comment]
Seems like it can't find a default browser to open for authentication, copying the URL it's trying to open, shown in the terminal, should allow it to continue. A dialog should probably be shown when it fails though. Logging in should work without a premium account, but functionality will be very limited.

**Comment by konrad1977** [comment]
Thanks got it running. But not much working in freemium version.

![b3bebee53d248d25e18454080617e9fdbb6b2161](https://user-images.githubusercontent.com/4384932/86353094-0b921d80-bc67-11ea-8475-f2853572b29d.png)

**Comment by kraxarn** [comment]
Please leave this open until it can properly handle not finding a default browser.
