### ISSUE TITLE
Double-click selection for active device not working

### ISSUE THREAD

**Issue by debdrup** [kraxarn/spotify-qt#162]
### System information
ABI: x86_64-little_endian-lp64
App version: v3.8
Build type: Release
D-Bus support: Yes
Device: bsd (Computer)
KCrash support: No
Kernel: freebsd 14.0-CURRENT
Product: FreeBSD 14.0-CURRENT
Qt version: 5.15.2
Window system: Wayland

### Detailed information
On initial setup, when the dialog box for selecting the active device pops up, it requires that you select the device and press OK, instead of simply double-clicking the device in question.

### What happens?
1. (Optionally) Reset config
2. Setup connectivity to Spotify Connect and play a song
3. Double-clicking the active device removes the dialogue box, but doesn't  select the active device, and when using `spotify-qt --dev` this line gets printed:
`me/player/play failed: Player command failed: No active device found`
4. Repeat ad nauseum until you realize that you have to select the device then press OK.

### What should happen?
Double-clicking the device should select it as the active device.

**Comment by kraxarn** [comment]
I'm not able to reproduce the issue, neither under Wayland nor X11. I did however rework the device selection a bit, which might help resolve the issue. If you're still experiencing issues, feel free to reopen the issue.
