### ISSUE TITLE
Allow user to resize or scale window.

### ISSUE THREAD

**Issue by smnbldwn** [kraxarn/spotify-qt#171]
I have a tiny screen on my netbook. (1024x600) Is it possible to make it so I can resize or scale the window to fit?  Thanks for an awesome piece of software!

**Comment by kraxarn** [comment]
Closing as this should work. If it still doesn't, please provide more details.

**Comment by WyntrHeart** [comment]
How exactly can I resize the window? The usual method of clicking and dragging the edges does nothing at all for me, the cursor doesn't change and clicking and dragging doesn't do anything

**Comment by WyntrHeart** [comment]
Nevermind, unchecking "Settings>Interface>Application Title Bar" fixed this for me

**Comment by kraxarn** [comment]
The borderless window should be able to be resized as well, but using native window borders will probably work better, due to borderless windows not being well supported natively with Qt.
