### ISSUE TITLE
Problems with Windows installation 

### ISSUE THREAD

**Issue by Tengas** [kraxarn/spotify-qt#174]
Below I have outlined my progress in trying to install this project on a Windows 10 computer. I believe the instructions are incomplete and could be improved. Based on my various attempts, I have compiled the following suggestions to improve the installation instructions for Windows: 

1. `cmake` needs to be run with the flag  `-G "MinGW Makefiles"` to avoid the error `CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage`
2. CMakeList.txt requires a reference to Qt5 (or maybe Qt6) for the variable `CMAKE_PREFIX_PATH`. Otherwise running cmake yields the error: 
 >   Could not find a package configuration file provided by "Qt5" with any of
>   the following names:
> 
>     Qt5Config.cmake
>     qt5-config.cmake ...
-------
**Attempts:**
 
I'm new to installing software from github but I'd really like to get this working on Windows 10. However, I'm not able to install it using the instructions provided. 

Steps taken: 

- Installed (via chocolately) cmake, make, git, g++ (with wingw) 
- git clone --branch stable https://github.com/kraxarn/spotify-qt.git (in PowerShell) 
- cd spotify-qt
- mkdir build
- cd build
- cmake .. 

the last step yields the following error: 

> C:\xxx\spofity-qt\build>cmake ..
> -- Building for: NMake Makefiles
> CMake Error at CMakeLists.txt:3 (project):
>   Running
> 
>    'nmake' '-?'
> 
>   failed with:
> 
>    The system cannot find the file specified
> 
> 
> CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> -- Configuring incomplete, errors occurred!
> See also "C:/xxx/build/CMakeOutput.log

The contents of CMakeOutput.log is  just "The system is: Windows - 10.0.19044 - AMD64" 

**Progress**: Googling I find the following SO: https://stackoverflow.com/questions/69338088/error-while-configuring-cmake-project-running-nmake-failed which suggests that I should append the command `-G "MinGW Makefiles"` which enabled me to proceed. 

The instructions say that Qt 5.9+/6.0+ works, I am not sure how to interpret these "+" exactly but it does not work with Qt 6.3. Running `cmake -S .. -B build -G "MinGW Makefiles"` yields the following error: 

> C:\xxx\spotify-qt\build  cmake -S .. -B . -G "MinGW Makefiles"
> CMake Error at CMakeLists.txt:38 (find_package):
>   By not providing "FindQt5.cmake" in CMAKE_MODULE_PATH this project has
>   asked CMake to find a package configuration file provided by "Qt5", but
>   CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5" with any of
>   the following names:
> 
>     Qt5Config.cmake
>     qt5-config.cmake
> 
>   Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
>   to a directory containing one of the above files.  If "Qt5" provides a
>   separate development package or SDK, be sure it has been installed.
> 
> 
> -- Configuring incomplete, errors occurred!

Progress: After some more [googling](https://stackoverflow.com/questions/15639781/how-to-find-the-qt5-cmake-module-on-windows) I found that augmenting the /spotify-qt/CMakeLists.txt to contain the line `set (CMAKE_PREFIX_PATH "C:/ProgramData/Qt/5.15.2/msvc2015_64/lib/cmake/Qt5")` which I put on line 6 (note the "/" instead of usual windows backslash "\\"). I found the several instances of Qt5Config.cmake and simply picked on at random. With this I was **finally** able to run `cmake -S .. -B . -G "MinGW Makefiles"` successfully. 

Unfortunately, running `make` I get new errors which don't even fit on one screen. The tail is such: 

> 4-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt3spt4authE[_ZTVN3lib2qt3spt4authE]+0x38): undefined reference to `QObject::event(QEvent*)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt3spt4authE[_ZTVN3lib2qt3spt4authE]+0x40): undefined reference to `QObject::eventFilter(QObject*, QEvent*)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt3spt4authE[_ZTVN3lib2qt3spt4authE]+0x48): undefined reference to `QObject::timerEvent(QTimerEvent*)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt3spt4authE[_ZTVN3lib2qt3spt4authE]+0x50): undefined reference to `QObject::childEvent(QChildEvent*)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt3spt4authE[_ZTVN3lib2qt3spt4authE]+0x58): undefined reference to `QObject::customEvent(QEvent*)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt3spt4authE[_ZTVN3lib2qt3spt4authE]+0x60): undefined reference to `QObject::connectNotify(QMetaMethod const&)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt3spt4authE[_ZTVN3lib2qt3spt4authE]+0x68): undefined reference to `QObject::disconnectNotify(QMetaMethod const&)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt11http_clientE[_ZTVN3lib2qt11http_clientE]+0x38): undefined reference to `QObject::event(QEvent*)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt11http_clientE[_ZTVN3lib2qt11http_clientE]+0x40): undefined reference to `QObject::eventFilter(QObject*, QEvent*)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt11http_clientE[_ZTVN3lib2qt11http_clientE]+0x48): undefined reference to `QObject::timerEvent(QTimerEvent*)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt11http_clientE[_ZTVN3lib2qt11http_clientE]+0x50): undefined reference to `QObject::childEvent(QChildEvent*)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt11http_clientE[_ZTVN3lib2qt11http_clientE]+0x58): undefined reference to `QObject::customEvent(QEvent*)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt11http_clientE[_ZTVN3lib2qt11http_clientE]+0x60): undefined reference to `QObject::connectNotify(QMetaMethod const&)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.rdata$_ZTVN3lib2qt11http_clientE[_ZTVN3lib2qt11http_clientE]+0x68): undefined reference to `QObject::disconnectNotify(QMetaMethod const&)'
> c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: lib/libspotify-qt-lib.a(mocs_compilation.cpp.obj):mocs_compilation.cpp:(.text$_ZN3lib2qt11http_clientD1Ev[_ZN3lib2qt11http_clientD1Ev]+0x33): undefined reference to `__imp__ZN7QObjectD2Ev'
> collect2.exe: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles\spotify-qt.dir\build.make:1847: spotify-qt.exe] Error 1
> make[1]: *** [CMakeFiles\Makefile2:455: CMakeFiles/spotify-qt.dir/all] Error 2
> make: *** [Makefile:135: all] Error 2

This might be because I installed an older version of qt (only one available from online installer with version 5.x is v. 5.15.). When I have more time I will retry with Qt 6 and add a reference to Qt6Config.cmake in the /spotify-qt/CMakeList.txt. Appreciate any additional help. 

---------------
Additionally I checked the file "CMakeList.txt" which has the confusing first line "cmake_minimum_required(VERSION 3.5)" but on the cmake-website (https://cmake.org/download/) the latest version is 3.23.2.

**Comment by Tengas** [comment]
Where can I find the binaries? (The ones I found on `https://github.com/kraxarn/spotify-qt` only link me to `https://github.com/kraxarn/spotify-qt/actions/workflows/windows-qt6.yml`)

**Comment by kraxarn** [comment]
Stable builds can be found on [the release page](https://github.com/kraxarn/spotify-qt/releases/latest), and unstable builds can be found on [the nightly page](https://kraxarn.github.io/spotify-qt-nightly).
