### ISSUE TITLE
Crossfade support

### ISSUE THREAD

**Issue by wdumez** [kraxarn/spotify-qt#177]
The official spotify client allows for crossfading of songs, with an adjustable slider for how many seconds it should fade. I would love to see this added in future.

**Comment by kraxarn** [comment]
As spotify-qt currently doesn't provide any playback functionality, this is outside the scope of spotify-qt. Moreover, as neither librespot nor spotifyd supports cross-fading, an option can't really be added either.

Closing as it's currently not possible. Please reopen if either librespot or spotifyd adds support for it :relaxed:
