### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by N-35** [kraxarn/spotify-qt#181]
Im using bspwm on Arch with the Linux kernel.

I've reinstalled the spotify-qt AUR package after using spotify-tui for a while, now whenever I try to launch it I get the Error Message

Unexpected response:
Refresh token revoked

This persists across reinstalls and/or reboots

**Comment by kraxarn** [comment]
Most likely a duplicate of #64. I have plans to handle this much better, but as a temporary fix, you can try starting spotify-qt with `--reset-credentials` to reauthenticate.

**Comment by kraxarn** [comment]
Closing this as this issue is now resolved.
