### ISSUE TITLE
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id

### ISSUE THREAD

**Issue by ngxson** [kraxarn/spotify-qt#182]
### System information

Fedora 36, using AppImage version

### What happens?

- Create spotify app as described in the "Configuring" section of README
- Copy/paste client ID + secret and authenticate

![image](https://user-images.githubusercontent.com/7702203/184547136-3a66a67a-a2df-4830-87da-732f16a4022c.png)

```
./spotify-qt-v3.9.AppImage
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.network.ssl: QSslSocket: cannot resolve EVP_PKEY_base_id
qt.network.ssl: QSslSocket: cannot resolve SSL_get_peer_certificate
qt.network.ssl: QSslSocket: cannot call unresolved function SSL_get_peer_certificate
[18:56:35] [err ] [json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal
```

**Comment by kraxarn** [comment]
This should now be fixed as of 289fd6a8f1e8c8854050991534fe3ec5d5f38c08. The build on the release page is now updated with the fix, so please try downloading it again and see if the new version works better :relaxed:
