### ISSUE TITLE
How to use on Windows?

### ISSUE THREAD

**Issue by fhtdtdj** [kraxarn/spotify-qt#184]
Couldn't get it running adequately on Windows 10 and a Free account.  Once client ID is configured and program is launched, program shows libraries and titles, etc. It does track and display what's being played in the opened official client, however trying to play different titles or pause from QT does nothing. Does playing/pausing titles only work with Premium accounts or...? Adding official client .exe in Settings > Spotify gives a error message: "Failed to apply settings "spotifyd path"" (despite nothing in the window saying spotifyd is required). So assuming spotifyd is the only supported client instead of official, but going to their github page I only see linux and macOS download links. If instructions could be clearer that would be greatly appreciated, thanks.

**Comment by instinctualjealousy** [comment]
The lack of documentation is truly something, right? Attempts were made to port spotifyd to Windows, but the only interested user with the coding knowledge required did the Cool Party Trick of retiring his only Windows machine and abandoning work on it. Commenters on said thread brought librespot as an option for using spotify-qt on Windows. I've only ever seen librespot integrated into a piece of software, not used as a running-separately software/daemon/or service. I'm gonna suss out what I can. It looks like you can use it with the official Spotify client... but what's the point of that? Two pieces of software to do what one can?

**Comment by kraxarn** [comment]
From the readme:
> **Note:** Controlling playback requires Spotify Premium.

It should however show an error message saying Premium is required, so if it doesn't, it's a bug.

Also, adding the official client is unsupported, as there's no command line interface for it, so you have to start it manually, which is supported. librespot should be supported under Windows afaik, but you have to compile it yourself, as no binaries are provided.

I've made some changes, clarifying that the path should only be for librespot or spotifyd, to avoid any further confusion.
