### ISSUE TITLE
Use spotifyd service (or keyring)

### ISSUE THREAD

**Issue by xisberto** [kraxarn/spotify-qt#19]
I have spotifyd configured to use keyring, but I can't make spotify-qt use the spotifyd running as a --user in systemd.

When I open spotify-qt, it starts a new spotifyd process and asks for my spotify password. And this second process doesn't get killed when I exit spotify-qt.

**Comment by kraxarn** [comment]
A way to save the password in a keyring is something I've planned, but it currently doesn't support it. You can make it use the global configuration for some more advanced settings.

And, yes, it currently doesn't close spotifyd when closing the application, there's a warning in the application for it though.
