### ISSUE TITLE
No access to library

### ISSUE THREAD

**Issue by coxackie** [kraxarn/spotify-qt#2]
Library grayed out, playlists showing up:

![Screenshot from 2020-03-29 20-39-02](https://user-images.githubusercontent.com/22049642/77858767-77df2a00-71fd-11ea-9dc0-4a260bb609ed.png)

on Arch linux, built from AUR package.

**Comment by kraxarn** [comment]
If you hover over it, it shows "not implemented yet" and it also says it's not implemented yet in the readme, so it's something planned for the future.

**Comment by coxackie** [comment]
I truly apologize. Looking forward to the missing features in the future. Out of curiosity, is a gtk-based version going to require a lot of changes and overhead?

**Comment by kraxarn** [comment]
I'm not too familiar with how GTK works, but if I understand it correctly, GTK is more of a GUI only thing, while Qt tries to provide everything you need. Having GTK as a GUI plugin and still using Qt for everything else, like networking, should be possible and not too difficult. It could be something to look further into in the future, when all features have been implemented.

**Comment by coxackie** [comment]
`GTK` is as much capable as `Qt` - it uses C instead of C++ for the most part. But, if you are aiming the Linux platform, you will get a lot more traction having this built with `GTK`, as the de facto DE in Linux is GNOME (Ubuntu, Fedora, Clear Linux, ...) It is worthwhile going that direction. There is Glade to help with the GUI, of course, but everything else is also possible that you are doing in `Qt` - it will just feel more native, and will reduce dependencies.

**Comment by kraxarn** [comment]
If this would use GTK, it would be using gtkmm (the C++ bindings) and available as an option. Just from my quick searching, there doesn't seem to be any networking capabilities in GTK, but yes, it's still probably just as capable when it comes to making GUIs. Also, I am aware GTK probably looks more native on non-KDE environments. Considering only networking and soon D-Bus is handled by Qt apart from the GUI, alternatives for those could be implemented to make Qt optional.
Might still be fun to play around with GTK and learn how it works, but it would probably have to wait until everything is implemented, unless you want to do a pull request. Feel free to open a new issue for it if you want to.

**Comment by coxackie** [comment]
I will open in time another issue for this. Waiting to see how MPRIS and such will work. You may close this issue for now.

**Comment by kraxarn** [comment]
This was mostly fixed in 84986197205c6a45ae05651ca4066205903cbf9a.
