### ISSUE TITLE
Cant play "Liked" songs

### ISSUE THREAD

**Issue by Hugo01** [kraxarn/spotify-qt#20]
Playing Songs from library works just fine except on the "liked" cattegory
You click to play a song and nothing happens

**Comment by kraxarn** [comment]
Do you get any error message? Are you running the latest stable version or directly from git?

**Comment by Hugo01** [comment]
No error message;
Running version 2.6-1, downloaded using AUR package  "yay -S spotify-qt";
Qt version 5.15.0;
Manjaro 20.0.3;

**Comment by philippgerard** [comment]
Same here, with message "Failed to start playback, invalid context uri".

App version: | v2.6
Current desktop: | X-Cinnamon
LSB release: | Manjaro Linux
Linux version: | 5.7.10-1-MANJARO
Qt version: | 5.15.0

**Comment by kraxarn** [comment]
Is this a regression from v2.6? Did it work in v2.5?

**Comment by avigloz** [comment]
I'm having the same issue; attempting to play any song from Liked Songs creates error `Failed to start playback, invalid context uri`

Your workaround works, though @kraxarn :+1:

**Comment by philippgerard** [comment]
The workaround doesn't work for me (unless I misunderstand the instructions, but my flow is super-simple: start the application, select "Liked", pick any song, double click to start playback, error.

I believe this error existed also in the previous version, but I can't be certain anymore, sorry.

**Comment by philippgerard** [comment]
P.S.: In the latest release the error message now reads `Failed to start playback: Player command failed: Restriction violated`. Just in case this helps narrow it down further.

**Comment by kraxarn** [comment]
Try single clicking a track and not double clicking. "Restriction violated" errors seems to happen if you try to play the same track twice. Either way, it's probably a separate issue, but if that resolves it, I'll just add a double click check.

**Comment by philippgerard** [comment]
> Try single clicking a track and not double clicking. "Restriction violated" errors seems to happen if you try to play the same track twice. Either way, it's probably a separate issue, but if that resolves it, I'll just add a double click check.

It also happens when I single click and yields the same message.

**Comment by kraxarn** [comment]
@philippgerard Try the latest update and see if the issue still occurs. If it does, please open a new issue as it's unrelated to this.
