### ISSUE TITLE
Removed songs break indexing of playlists

### ISSUE THREAD

**Issue by ptrcnull** [kraxarn/spotify-qt#209]
### System information
```
ABI: x86_64-little_endian-lp64
App version: v3.9
Build type: MinSizeRel
Current desktop: sway
D-Bus support: Yes
Device: katsumi (Speaker)
KCrash support: No
Kernel: linux 6.1.11-0-lts
Product: Alpine Linux edge
Qt version: 6.4.0
Window system: Wayland
```
(also happens on master)

### Detailed information
`spotify:track:0lMrWcrVXHPEuVBuc0nRzZ` (was `Alan Walker - Spectre`) was removed by Spotify a while ago, probably due to copyright disputes between Alan Walker, NCS and Sony Music. I still have this song in my library, but the metadata is empty and it somehow breaks spotify-qt playlist indexing.

### What happens?
- double-click on a song in the same playlist as the previously mentioned song
- spotify-qt plays the next song instead of the selected one

### What should happen?
- spotify-qt should play the selected song

**Comment by kraxarn** [comment]
Do you have any playlist I can use for testing that's broken? I found some tracks maked as Unavailable in old playlists of mine, but the names are still displayed correctly, and indexing still works correctly for the other tracks. Or maybe it was fixed by 6fac55e7bbc0980c191d2c3f8857a6809b8b354c?

**Comment by ptrcnull** [comment]
A playlist to reproduce this can be found here: https://open.spotify.com/playlist/3Le6YWcg7slDSUXnWYESp8

**Comment by kraxarn** [comment]
This has been pretty inconsistent and difficult to reproduce, but this issue only seems to only happen when playing with an official native client, like the desktop client or mobile app. At least when using librespot, so I assume spotifyd as well, it works like expected. Interestingly enough, it also works when using the web player.

Not entire sure on how to solve it, might add an option for it or something, even if I don't really like that solution.
