### ISSUE TITLE
Audio features & lyrics crash application

### ISSUE THREAD

**Issue by philippgerard** [kraxarn/spotify-qt#21]
Hi @kraxarn :)

when I right click on (it seems, tried a dozen or so) any song and select either option of "Lyrics" or "Audio features" the application crashes completely. Is the expected behavior because the functionality is only mocked in the interface?

```
App version: | v2.7
Current desktop: | X-Cinnamon
LSB release: | Manjaro Linux
Linux version: | 5.7.10-1-MANJARO
Qt version: | 5.15.0
```

Best,
Philipp

**Comment by kraxarn** [comment]
oops :sweat_smile:
