### ISSUE TITLE
No active device found

### ISSUE THREAD

**Issue by tigaente** [kraxarn/spotify-qt#210]
### System information
ABI: x86_64-little_endian-lp64
App version: v3.9
Build type: Release
Current desktop: KDE
D-Bus support: Yes
Install type: System
KCrash support: Yes
Kernel: linux 6.2.1-arch1-1
Product: Arch Linux
Qt version: 5.15.8
Window system: X11

{
    "General": {
        "check_for_updates": true,
        "close_to_tray": true,
        "fallback_icons": false,
        "fixed_width_time": true,
        "hidden_song_headers": [],
        "last_version": "v3.9",
        "last_volume": 20,
        "media_controller": true,
        "notify_track_change": false,
        "playlist_order": 0,
        "refresh_interval": 3,
        "relative_added": true,
        "show_changelog": true,
        "song_header_sort_by": -1,
        "style": "Oxygen",
        "style_palette": 0,
        "track_list_resize_mode": 0,
        "track_numbers": 1,
        "tray_album_art": false,
        "tray_icon": true,
        "tray_light_icon": false
    },
    "Qt": {
        "album_size": 0,
        "custom_font_name": "",
        "custom_font_size": 0,
        "mirror_title_bar": false,
        "system_title_bar": true
    },
    "Spotify": {
        "always_start": true,
        "backend": "",
        "bitrate": 160,
        "device_type": 0,
        "disable_discovery": false,
        "global_config": false,
        "keyring_password": true,
        "max_queue": 500,
        "start_client": true
    }
}

There is also an account section that wasn't copied. It contains some client_ids, secrets and tokens which, for now, I will not paste here. I use librespot 0.5.0-dev a211ff9 as the backend. 

### Detailed information
In the past, I used spotify-qt to play music from spotify through the librespot backend. It used to work fine. However, when I tried today, no music was played and I only receive the error "No active device found". I tried logging out and back in again. I also completely remove the config and logged in again but it didn't change anything.

### What happens?
I open one of my playlists in spotify-qt. I double-click on any song. I receive the following error:
[18:03:34] [err ] Request failed: Error transferring https://api.spotify.com/v1/me/player/play - server replied: Not Found
[18:03:34] [err ] me/player/play failed: Player command failed: No active device found

### What should happen?
It should start playing music.

**Comment by tigaente** [comment]
Debug Mode reveals the following command line is used to start the backend. It results in an error when running manually, though:
`/usr/bin/librespot --bitrate 160 --username XXX --password YYY --name spotify-qt (librespot) --initial-volume 100 --autoplay --cache /home/xyz/.cache/kraxarn/spotify-qt/librespot
bash: syntax error near unexpected token (`

So.. it might be the space in the name. But when changing the name to spotify-qt only, this is returned:
`[2023-03-03T18:45:17Z INFO  librespot] librespot 0.5.0-dev a211ff9 (Built on 2023-02-06, Build ID: 1675719137, Profile: release)
[2023-03-03T18:45:17Z ERROR librespot] Invalid --autoplay / -A: "--cache"
Valid --autoplay / -A values: on, off`

Apparently, the options have changed in librespot.

**Comment by kraxarn** [comment]
librespot v0.5.0 support was fixed in 769474121366eb95f4c0df98f34e6df58c761023, which will be available in spotify-qt v3.10. As a workaround, either start it manually with `--autoplay` removed, or just use librespot v0.4.2.

**Comment by charlesmulder** [comment]
Hi. I am running `spotify-qt v3.10` and it looks like `--autoplay` is still being passed.

**Comment by kraxarn** [comment]
The `--autoplay` option was added back into librespot, but with changed syntax, which makes it incompatible. This was fixed in #217 and will be available in v3.11.
