### ISSUE TITLE
[UI] Hiding "Added" column is not persisted when navigating

### ISSUE THREAD

**Issue by ypislon** [kraxarn/spotify-qt#219]
### System information

```
ABI             : x86_64-little_endian-lp64
App version     : v3.10
Build type      : Release
Current desktop : XFCE
D-Bus support   : Yes
Device          : spotifyd deamon (Speaker)
KCrash support  : Yes
Kernel          : linux 6.1.30-1-MANJARO
Keychain support: Yes
Platform        : xcb
Product         : Manjaro Linux
Qt version      : 5.15.9
```

### Detailed information

When trying to hide the column "Added" for the currently displayed music in the center panel of the UI, the column is hidden, but is visible again after switching to another playlist/album. The checkbox to show the "Added" column in the context menu is still deselected, but the column is visible. The "Added" column seems to be the only column which is affected, every other option to hide/show columns is persistent when navigating. 

### What happens?

- User right-clicks columns in main panel 
- User selects "columns to show"
- User unchecks "Added"
- UI is updated and "Added" column is hidden
- User navigates to another album/playlist etc.
- UI is updated and "Added" column is shown again, while the option in the context menu is still deselected 

### What should happen?

- User right-clicks columns in main panel 
- User selects "columns to show"
- User unchecks "Added"
- UI is updated and "Added" column is hidden
- User navigates to another album/playlist etc.
- UI is persistent and "Added" column is hidden until selected again in the context menu

**Comment by kraxarn** [comment]
Closing as #267 has now been merged.
