### ISSUE TITLE
Can't play "Liked" playlist

### ISSUE THREAD

**Issue by philippgerard** [kraxarn/spotify-qt#22]
In v2.8 (same as before, but as requested in a new ticket), I can't play liked songs. The error message is still a "restriction violated". Other playlists work just fine.

> App version: | v2.8
> Current desktop: | X-Cinnamon
> LSB release: | Manjaro Linux
> Linux version: | 5.7.12-1-MANJARO
> Qt version: | 5.15.0

Happy to provide more data for debugging etc., just let me know what would help.

**Comment by kraxarn** [comment]
What playback device are you using? spotifyd?

**Comment by juliendechaud** [comment]
my spotifyd say this : spotifyd[5446]: No more tracks left in queue

App version: | v2.8
Current desktop: | XFCE
Linux version: | 5.7.11-zen1-1-zen
Qt version: | 5.15.0

**Comment by philippgerard** [comment]
> What playback device are you using? spotifyd?

Yes, spotifyd with a global config.

**Comment by kraxarn** [comment]
Was finally able to find some tracks to trigger this bug consistently. The issue seems to be in the Spotify API with some tracks, but I'm unsure of the actual cause. Please reopen if the issue still occurs in v2.12.

**Comment by lilongueti** [comment]
i'm still having this issue on 3.0, sometimes it just goes to play my top playlist instead, spotifyd just throws the "No more tracks left in queue".
also i don't know if this could be related with #29 , but my library is 1400+ songs
