### ISSUE TITLE
Duplicate of playlist names in add playlist

### ISSUE THREAD

**Issue by kukus888** [kraxarn/spotify-qt#221]
### System information
ABI: x86_64-little_endian-lp64
App version: v3.9
Build type: RelWithDebInfo
Current desktop: KDE
D-Bus support: No
Device: spotify-qt (librespot) (Speaker)
Install type: System
KCrash support: No
Kernel: linux 5.14.21-150500.53-default
Product: openSUSE Leap 15.5
Qt version: 5.15.8
Window system: X11

### Detailed information
1. Go to any playlist or queue, click right on a song.
2. Hover over add to playlist, until playlist list appears.
3. After that, hover outside the 'add to playlist' menuitem, until the playlist list disappears. 
4. Repeat step 2. Playlist names are now duplicated
5. For amusement, repeat steps 2 and 3, until your screen is filled with your playlists

### What happens?
The add to playlist submenu gets filled with duplicates of your playlists.

### What should happen?
There should not be any duplicates of playlists in add to playlist menu.

**Comment by kraxarn** [comment]
This was already fixed in v3.10 from 673b536ec0772c7949bac80625e3901fc57aec92, I guess I just forgot to document it in the changelog, oops.
Please update to the latest version and try again ☺️
