### ISSUE TITLE
Pass custom arguments to backend process

### ISSUE THREAD

**Issue by instinctualjealousy** [kraxarn/spotify-qt#223]
In my case, I'm on Windows 10 using librespot as a backend. There are two things I wanted to be able to do that I cannot figure out after getting it all set up- which is configuring normalization and the backend output device. If running librespot from terminal, it'd be as easy as adding a couple arguments to the process. It'd be nice to be able to append your own arguments, so in the meantime people won't have to feature request increasingly uncommon settings into the spotify-qt UI. I figure this wouldn't be hard to implement compared to feature-specific alternatives, as well.

**Comment by instinctualjealousy** [comment]
I've actually reworked how I'm doing things and I personally don't need in-program config for this, but it'd still be a good feature for someone who wants spotify-qt to manage the settings and running of it.

**Comment by kraxarn** [comment]
Fixed in #232
