### ISSUE TITLE
seekbar increments forward while paused when using librespot-java as backend (otherwise works great)

### ISSUE THREAD

**Issue by instinctualjealousy** [kraxarn/spotify-qt#224]
I'm not going to file this as a BUG per-se, because it may be the fault of librespot-java, and it isn't really intended to be used with spotify-qt as a first-class citizen. I'm using it because shuffle actually [works right](https://github.com/kraxarn/spotify-qt/issues/186#issuecomment-1321039840), which can't be said of Rust librespot.

Much to my dismay, the Java version is the more well-supported version right now (ugh RAM), and I do think it'd be a good third target for spotify-qt in the future- but that's neither here nor there. I could dish out the "sick burns", but I can't program at all and I understand many projects struggle to find support.

This is the relevant librespot-java issue:
librespot-org/librespot-java#350

It might still be worth fixing on spotify-qt's end, as the real Spotify client on my Android phone doesn't get seek-confused by librespot when Connected to it and paused. I don't know the beginning or end of what's actually going on, that it would actually increment in this way. Feels like some data is either getting misinterpreted on spotify-qt's end, or the real Spotify client is ignoring that data. It would also have to be considered that whatever "fix" that needed to be done wouldn't break Rust librespot support.

Feel free to close this issue if you feel that it is not valid to spotify-qt!

**Comment by kraxarn** [comment]
I've also noticed this, but similar to the broken shuffle with other clients, I don't see this as a bug with spotify-qt itself. It's also possible to seek while paused, so it's not easily fixed, or worked around, either. I assume the bug only occurs with applications using the Web API, and thus the official clients aren't affected, but that's just a guess.
