### ISSUE TITLE
Playlist isn't showing anything

### ISSUE THREAD

**Issue by Vixtron** [kraxarn/spotify-qt#23]
The playlist window is empty for every playlist I saved on Spotify.

**Comment by kraxarn** [comment]
Please provide some system details. You can get basic information from Settings > About > System info

**Comment by Vixtron** [comment]
![Screenshot_20200807_095030](https://user-images.githubusercontent.com/22355590/89622499-6edd2400-d893-11ea-9d7c-6b5daeb05d69.png)
