### ISSUE TITLE
Hoping For A Version That Works With macOS Snow Leopard.

### ISSUE THREAD

**Issue by theanthonydavenport** [kraxarn/spotify-qt#233]
It has been a hassle trying to get a Spotify Client working on Snow Leopard, so, I was hoping that a version of this lightweight software could be made for it.
(Intel)

**Comment by RokeJulianLockhart** [comment]
@theanthonydavenport, Snow Leopard was released in 2009-08-28. Why would anyone support an OS that old? You're practically using Windows XP.

**Comment by kraxarn** [comment]
As it isn't supported by neither Qt nor Apple, I won't provide any pre-built binaries for it, but if you manage to get your hands on an old enough version of Qt, you can compile from source yourself and I can try to help out where I can :)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/kraxarn/spotify-qt/issues/233#issuecomment-1826874178

Per https://stackoverflow.com/a/65210788/9731176, I believe that this is prohibitively difficult to such an extent that it would be infeasible for probably most except the most talented software developer intimately familiar with Qt. If my assessment is accurate, this is probably worth closing, @kraxarn.

**Comment by kraxarn** [comment]
Closing as it's not an issue with the application itself. If you want to continue the conversation, I'll move it to a discussion instead.
