### ISSUE TITLE
Liked Songs playlist unavailable.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [kraxarn/spotify-qt#235]
### System information

<blockQuote>

*Type*           | *Data*
-----------------|--------------------------
ABI              | x86_64-little_endian-lp64
App version      | v3.10
Build type       | RelWithDebInfo
Current desktop  | KDE
D-Bus support    | No
Install type     | System
KCrash support   | No
Kernel           | linux 6.6.1-1-default
Keychain support | No
Platform         | xcb
Product          | openSUSE Tumbleweed
Qt version       | 5.15.11

</blockQuote>

### What happens?

The https://open.spotify.com/collection/tracks playlist isn't available. See https://github.com/kraxarn/spotify-qt/discussions/234#discussion-5856150:

<blockQuote>

It's not visible:

> ![20231115T234653GMT](https://github.com/kraxarn/spotify-qt/assets/42837531/890280f4-3269-4ad1-b714-07041f66b112)

</blockQuote>

### What should happen?

It should be available, especially because https://github.com/kraxarn/spotify-qt knows which tracks are liked.

**Comment by kraxarn** [comment]
It should be the same as "Liked tracks", just a slightly different name for no real reason.
