### ISSUE TITLE
Not working on FreeBSD due to incompatible Qt library

### ISSUE THREAD

**Issue by i-lost-my-bagel** [kraxarn/spotify-qt#240]
### System information
FreeBSD 14.0-Release

### Detailed information
Cannot run spotify-qt because the qt library on my system is incompatible with the one on my system

### What happens?
![image](https://github.com/kraxarn/spotify-qt/assets/32345477/a6c94c0a-8eae-45aa-a1c4-fa2292d2b1a6)

**Comment by kraxarn** [comment]
Sounds like an issue with the packaging and not the application itself.

Try to compile it from source if you can, and if that works, try to contact the maintainer of the package instead.

**Comment by i-lost-my-bagel** [comment]
sorry for taking so long to reply. I've been really busy. I tried building it from source but I'm still having the same issue so I think it's a problem with the application.

![image](https://github.com/kraxarn/spotify-qt/assets/32345477/025500a6-9938-4ac6-984f-4f33365b7f81)

**Comment by herrhotzenplotz** [comment]
@i-lost-my-bagel Using FreeBSD and spotify-qt every day I have never seen this issue. You should possibly do a full pkg upgrade, e.g.:

```console
# pkg update -f
# pkg upgrade -f
# pkg autoremove
# pkg clean
```

Note that this will force-reinstall **all** packages - thus possibly eliminating the weird dependency state you're in. Depending on how much stuff you have installed this may take a little while.

Also, try checking what the spotify-qt binary is actually linked against with ldd and whether these libraries make sense.

**Comment by kraxarn** [comment]
Thank you @herrhotzenplotz for providing some help, I have no experience with BSD 😅 
Closing as it's most likely not an issue with the application itself.
