### ISSUE TITLE
Feature request: libshout output with interface

### ISSUE THREAD

**Issue by mustafejen** [kraxarn/spotify-qt#258]
As far as I know, the Spotify stream is encoded in vorbis format which should be possible to somehow be fed to an icecast server without decoding into raw audio first.

I think like:

stream from spotify ------------------->decode and send to sound server
                            tee         |
                                           ---------->forward to [https://github.com/xiph/Icecast-libshout](url) which gets it's options from the interface libshout section

Maybe I am overly optimistic

**Comment by kraxarn** [comment]
It might be possible, but as spotify-qt currently has no playback functionality, this is currently way out of scope of the application. You could probably set something up manually though, and then control it from spotify-qt.
