### ISSUE TITLE
Search in sidebar fails

### ISSUE THREAD

**Issue by tannenfreund87** [kraxarn/spotify-qt#268]
### System information
ABI            : x86_64-little_endian-lp64
App version    : v3.11 (843057b8)
Build type     : 
Current desktop: KDE
D-Bus support  : Yes
Device         : Librespot (Computer)
KCrash support : No
Kernel         : linux 6.11.8-1-default
Platform       : xcb
Product        : openSUSE Tumbleweed
Qt version     : 6.8.0

### Detailed information
Since a few days, sidebar search doesn't show any results anymore. Maybe spotify changed something in the API? The error shows in the official release as well in a fresh compile of master. Independent of OS, get the same error on Windows.

`[10:37:00] [err] search?q=metallica&type=album,artist,playlist,track,show&limit=50&market=from_token failed: [json.exception.out_of_range.403] key 'available_markets' not found`
### What happens?
Open sidebar, type in search term, search bar grays out, no search results shown. Error message above.
### What should happen?
Search results should show.

Thank you and take your time!

**Comment by RafGamer** [comment]
It seems like the spotify api isn't returning the `available_markets` key when a market is specified in the request.
It works when an if statement is added here to check if the key exists or not: https://github.com/kraxarn/spotify-qt/blob/843057b89ab6821c13aa3549174803d49450de4a/lib/src/spotify/show.cpp#L10

**Comment by kraxarn** [comment]
Thanks for finding, and reporting, it! :relaxed:
"Available markets" isn't even used, and I can't remember what kind of use it would have, so I just removed it completely and now it works fine again. Weird how they just removed it though, since it used to work just fine.
