### ISSUE TITLE
Librespot no longer supports password authentication

### ISSUE THREAD

**Issue by TrialDragon** [kraxarn/spotify-qt#269]
### System information
ABI             : x86_64-little_endian-lp64
App version     : v3.11 (83bfc5df)
Build type      : Release
Current desktop : COSMIC
D-Bus support   : Yes
KCrash support  : No
Kernel          : linux 6.11.6-200.fc40.x86_64
Keychain support: Yes
Platform        : xcb
Product         : Fedora Linux 40 (Workstation Edition)
Qt version      : 6.6.1

### Detailed information
When using Librespot, it complains about
```
[03:07:01 PM] [err] [2024-11-27T23:07:01Z INFO  librespot] librespot 0.6.0 VERGEN_IDEMPOTENT_OUTPUT (Built on 2024-11-27, Build ID: zdSg771T, Profile: release)
[03:07:01 PM] [err] [2024-11-27T23:07:01Z ERROR librespot] Invalid `--password` / `-p`: Password authentication no longer supported, use OAuth
```
Suggesting that the password authentication Spotify-qt uses is no longer supported, make Librespot unusable by Spotify-qt.

### What happens?
Select Librespot 0.6.0 as the desired client, login, and run it. Watch it not run due to not supporting password authentication anymore.

### What should happen?
Spotify-qt could hopefully support Oauth to allow Librespot to be used (or just say Librespot is unsupported now if you can't support Oauth).

**Comment by kraxarn** [comment]
It should be working as of around c79c4acd4850ca520552cb0a95cc4e33f5059941, so please try the nightly build, or just wait for the next stable release, which should hopefully be out in a couple of days ☺️
