### ISSUE TITLE
Spotify Web API Changes

### ISSUE THREAD

**Issue by RafGamer** [kraxarn/spotify-qt#270]
A lot of features don't work anymore because Spotify changed their Web API.

https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api

The audio features option, for example, can be completely removed now.

Spotify-qt throws a lot of errors when navigating the UI because of these changes.

I think the biggest problem is, that playlists that are made by Spotify can't be accessed anymore. The API returns `null` for them.

I don't know if there is another way to implement this. But if there isn't, spotify-qt should at least filter these playlists out because the playlists tab now looks really weird with all those empty fields.

**Comment by kraxarn** [comment]
Thanks a lot for letting me know! Especially since Spotify sure didn't :/

For some reason, I don't have any issues (yet) with my own app, so I didn't even notice the changes, but I've now made some changes to be more compatible with the new changes.

**Comment by meven** [comment]
This has caused many complaints: https://community.spotify.com/t5/Spotify-for-Developers/Changes-to-Web-API/td-p/6540414
