### ISSUE TITLE
I can see my playlists - but cannot play the songs

### ISSUE THREAD

**Issue by jaykonrad** [kraxarn/spotify-qt#272]
### Discussed in https://github.com/kraxarn/spotify-qt/discussions/271

<div type='discussions-op-text'>

<sup>Originally posted by **jaykonrad** December  2, 2024</sup>
Hi guys - I need some help! I have an old iMac running Ubuntu 18.04. I want to listen to Spotify. So I installed Spotify-QT, connected it to my Spotify (which worked, it is showing me all playlists) and then compiled and installed librespot.

Unfortunately, librespot was in /home/pikewerfer/.cargo/bin - and Spotify-QT would not accept this as a path to librespot. I therefore cp the librespot binary to /home/pikewerfer/target/release/. Now the client starts, and Spotify-QT is happy.

However, when I try to play a song, I get an error message telling me "Failed to resume playback: Player command failed: No active device found". When I check the Spotify-QT settings, it says that the client is running. When I check the Spotify-QT logs, I find three error messages:

This happens first and is in the Spotify log: [13:11:19] [err] /home/pikewerfer/target/release/librespot: error while loading shared libraries: [libasound.so](http://libasound.so/).2: cannot open shared object file: No such file or directory

Then this happens in App log: [13:11:26] [err] Request failed: Error transferring https://api.spotify.com/v1/me/player/play - server replied: Not Found

Then this in the App log: [13:11:26] [err] me/player/play failed: Player command failed: No active device found

When I do sudo apt-get install libasound2, Ubuntu tells me I already have the latest package. I am stuck - what else could I do to solve this?</div>

**Comment by kraxarn** [comment]
Closing as the discussion is already resolved.
