### ISSUE TITLE
weird ordering of tracks when ordered by track number

### ISSUE THREAD

**Issue by circled-square** [kraxarn/spotify-qt#29]
### System information

ABI: | x86_64-little_endian-lp64
-- | --
App version: | v2.12
Current desktop: | XFCE
Kernel: | linux 5.4.67-1-MANJARO
Product: | Manjaro Linux
Qt version: | 5.15.1

### Detailed information

when tracks are ordered by # the tracks [1000, 1009] come before 101, [1010, 1019] come before 102, etc. This doesn't happen with numbers under 100

**Comment by kraxarn** [comment]
Kind of intentional as it only creates padding for 3 characters, just didn't expect anyone to have 1000 or more tracks in a playlist. Should probably have it automatically set the padding depending on how many tracks there are :smile:

**Comment by ehaupt** [comment]
I ran into the same issue with > 600 songs in my _Liked_ playlist.

There used to be a 10000-song cap but according to [this](https://www.theverge.com/2020/5/26/21270409/spotify-song-library-limit-removed-music-downloads-playlists-feature) verge post, the cap was recently removed altogether.
