### ISSUE TITLE
Authentication `INVALID_CLIENT: Invalid redirect URI`

### ISSUE THREAD

**Issue by a-andreyev** [kraxarn/spotify-qt#3]
Hello! Interesting project! :+1: 

As subject points, I'm getting `INVALID_CLIENT: Invalid redirect URI` when trying to auth (with my personal client ids, etc). Didn't received any errors about tcp server via cli output though :thinking: 
Any hints what to check twice?

**Comment by kraxarn** [comment]
Make sure you added the address `http://localhost:8888` to "Redirect URIs" and not "Website".

**Comment by a-andreyev** [comment]
you're right! I've missed that at spotify app dashboard settings. Working now with *spotifyd*

**Comment by kraxarn** [comment]
Should probably clarify it a bit :p

**Comment by yshnv** [comment]
Goto Spotify Dashboard -> Edit Settings -> Add `http://localhost:8888` to **Redirect URIs**

**Comment by RokeJulianLockhart** [comment]
@kraxarn, although [`http://localhost:8888`](http://localhost:8888) has been replaced with what [`pull/281`](https://github.com/kraxarn/spotify-qt/pull/281#issue-2859839653) describes: [^1] [^3]

[^3]: [`wiki/Frequently-Asked-Questions/dcf8e370e2817eb11458e4f6e2d00292e77a90b1`](https://github.com/kraxarn/spotify-qt/wiki/Frequently-Asked-Questions/dcf8e370e2817eb11458e4f6e2d00292e77a90b1#:~:text=Add%20%22http://127%2E0%2E0%2E1:8888%22%20to%20%22Redirect%20URIs%22%2E)

[^1]: [`community.spotify.com/t5/Spotify-for-Developers/redirect-uri-doesn-t-seems-to-support-dynamic-port/m-p/7342510/highlight/true#M20491`](https://community.spotify.com/t5/Spotify-for-Developers/redirect-uri-doesn-t-seems-to-support-dynamic-port/m-p/7342510/highlight/true#M20491:~:text=For%20me%2C%20even%20http://localhost:8888%20produces,cause%20appears%20to%20be%20https://developer%2Espotify%2Ecom/documentation/web%2Dapi/tutorials/migration%2Dinsecure%2Dredirect%2Duri%2E)

> [`http://127.0.0.1:8888/`](http://127.0.0.1:8888/)

…when I enter it, I am `.replace`'d to [`accounts.spotify.com/authorize?client_id=30a6411284824619b108c67bff0d1e54&response_type=code&redirect_uri=http://127.0.0.1:8888&scope=playlist-read-collaborative%20playlist-read-private%20playlist-modify-private%20playlist-modify-public%20user-follow-read%20user-follow-modify%20user-library-modify%20user-library-read%20user-modify-playback-state%20user-read-currently-playing%20user-read-playback-state%20user-read-private%20user-read-recently-played%20streaming%20user-read-email%20user-top-read`](https://accounts.spotify.com/authorize?client_id=30a6411284824619b108c67bff0d1e54&response_type=code&redirect_uri=http://127.0.0.1:8888&scope=playlist-read-collaborative%20playlist-read-private%20playlist-modify-private%20playlist-modify-public%20user-follow-read%20user-follow-modify%20user-library-modify%20user-library-read%20user-modify-playback-state%20user-read-currently-playing%20user-read-playback-state%20user-read-private%20user-read-recently-played%20streaming%20user-read-email%20user-top-read), whereupon I observe:

> `INVALID_CLIENT`: Invalid redirect URI

To confirm this:

1. <p></p>

   <img width="636" height="1404" alt="Image" src="https://github.com/user-attachments/assets/8a72dd2b-0613-4d8c-805e-32768c9fbd0d" /> [^2]

   [^2]: [`developer.spotify.com/dashboard/30a6411284824619b108c67bff0d1e54#newRedirectUri`](https://developer.spotify.com/dashboard/30a6411284824619b108c67bff0d1e54#newRedirectUri:~:text=Website-,Redirect%20URIs,-*%28required%29)

   <p></p>

1. <p></p><img width="605" height="254" alt="Image" src="https://github.com/user-attachments/assets/9233423e-1778-432f-8259-7e7ea0392d10" /><p></p>

   I do enter the secret. I've even rotated it.

1. <p></p><img width="1276" height="356" alt="Image" src="https://github.com/user-attachments/assets/66bae3bc-fc14-4119-a5e6-736c8b1a5ec6" /><p></p>

#### My Environment

<blockquote>

~~~YAML
Name        : spotify-qt
Version     : 4.0.2
Release     : 1.fc43
Architecture: x86_64
Install Date: Sun 15 Feb 2026 23:28:07 GMT
Size        : 2244880
Signature   :
              RSA/SHA256, Sat 07 Feb 2026 19:26:55 GMT, Key ID b55cc4ab0d6e3f64
              RSA/SHA256, Sat 07 Feb 2026 19:26:55 GMT, Key ID b55cc4ab0d6e3f64
Source RPM  : spotify-qt-4.0.2-1.fc43.src.rpm
Build Date  : Sat 07 Feb 2026 19:21:33 GMT
Build Host  : aws-x86-64-normalreserved-prod-01995287-20260207-191900
Vendor      : Fedora Copr - user kraxarn
~~~

</blockquote>
