### ISSUE TITLE
Allow user to change spotifyd backend

### ISSUE THREAD

**Issue by boomlinde** [kraxarn/spotify-qt#31]
Currently, spotify-qt can spawn a spotifyd instance but will always supply the argument `--backend pulseaudio` if spotifyd has been built with pulseaudio support. For an ALSA user with a distribution maintained build of spotifyd that supports pulse, this is inconvenient and means that I can't use the feature.

**Comment by kraxarn** [comment]
It's mostly like that because of the volume control, which (currently) only supports PulseAudio, but an option to manually select a backend is probably good, I agree.

**Comment by boomlinde** [comment]
Thank you for the prompt response. For now, I've recompiled spotifyd without pulse support, which is a viable workaround for the time. I really like spotify-qt so far!

**Comment by kraxarn** [comment]
Glad to hear :relaxed:
