### ISSUE TITLE
Can't start the 'liked songs' playlist

### ISSUE THREAD

**Issue by lilongueti** [kraxarn/spotify-qt#33]
i'm starting a new issue because i don't think i'm able to re open #22 , but im still affected by this on v3.0.
also i don't know if this is related with #29 , but my library is 1400+ songs.
spotifyd throws the "No more tracks left in queue" message and sometimes it starts playing my top playlist instead

edit: log message and system info
[5:38 PM] [warn] Spotifyd/librespot was compiled without PulseAudio support

ABI: | x86_64-little_endian-lp64
-- | --
App version: | v3.0
Current desktop: | X-Cinnamon
Device: | Spotifyd@Yamaguchi (Speaker)
Kernel: | linux 5.9.1-1-default
Product: | openSUSE Tumbleweed
Qt version: | 5.15.1

**Comment by lilongueti** [comment]
just built 3.1 and started getting a couple more messages,
firstly a restriction violated one, realized its because there are songs on my library that aren't available on spotify any more
after removing all of them i started getting this one:
[1:10 PM] [err ] /v1/me/player/play failed: Invalid context uri
also i've been trying to debug the project myself, i'm pretty noob on c++ but i'd love to try and help you find the issue, how ever i keep getting a message from gdb complaining about debug symbols being missing, am i missing something on the cmake lists?
Cheers

**Comment by lilongueti** [comment]
i've upgraded to v3.1 and now im getting this message
[err ] /v1/me/player/play failed: Invalid context uri
and none on spotifyd

**Comment by lilongueti** [comment]
i've been trying to debug the TracksList::clicked but after reaching the breakpoint gdb will complain about the function not having the line information for the function, do i have to change something on the cmakelists to get it to generate them properly?

**Comment by kraxarn** [comment]
I think this line is very suspicious:
https://github.com/kraxarn/spotify-qt/blob/acf0f4907c6527c4639f74d047f1c02b59d59eda/src/list/trackslist.cpp#L73
Probably what's causing issues is the "playlist" contains more than 500 tracks, and it tries to play from your current context instead, which fails for library options. So, it instead tries to find the track you're trying to play from the last playlist you had opened.

Either way, calling CMake with `-DCMAKE_BUILD_TYPE=Debug` should be enough.

**Comment by lilongueti** [comment]
well i managed to get to debug it, how ever it seems to me like besides that line, sending the whole list doesn't fit into the QNetworkAccessManager buffer.
on this line:
https://github.com/kraxarn/spotify-qt/blob/acf0f4907c6527c4639f74d047f1c02b59d59eda/src/spotify/spotify.cpp#L90
it goes to qt method:
```
QNetworkReply *QNetworkAccessManager::put(const QNetworkRequest &request, const QByteArray &data)
{
    QBuffer *buffer = new QBuffer;
    buffer->setData(data);
    buffer->open(QIODevice::ReadOnly);

    QNetworkReply *reply = put(request, buffer);
    buffer->setParent(reply);
    return reply;
}
```
it gets up to the 'buffer->setData(data)' statement and exits right back to Spotify::put function without any message

if this is correct, chopping the list into parts and adding them to queue could be the solution

**Comment by kraxarn** [comment]
I don't think sending all tracks is the right solution. Even if they would all be added to the queue, it would make the queue stop working as a queue, as queued tracks would play last instead of first. Besides, i believe the queue carries over when you start playing something else. The official client can play without adding the tracks themselves, so i feel like there should be a better solution.

**Comment by kraxarn** [comment]
Added a new setting that allows setting a limit for how many tracks can be queued at once, by default setting the limit at 500. This should make it so it only plays 500 tracks from the list instead of trying to play all of them. Not a perfect solution, but should work.
