### ISSUE TITLE
Latest release has version v0.0 in the About dialog

### ISSUE THREAD

**Issue by kkga** [kraxarn/spotify-qt#34]
### System information

```
ABI: | x86_64-little_endian-lp64
-- | --
App version: | v0.0
Device: | Spotifyd@void (Speaker)
Kernel: | linux 5.9.7_1
Product: | void
Qt version: | 5.15.1
```

### Detailed information
Built locally following the README instructions, however the About dialog shows an incorrect version number.
![image](https://user-images.githubusercontent.com/1460122/99098709-6c087280-25ea-11eb-9cce-8a292c18c474.png)

**Comment by kraxarn** [comment]
The version is fetched from Git, so if you just downloaded the archive for the latest version and compiled, you have to manually specify the version through CMake with `-DGIT_TAG=`, but if you clone from Git, it should get the correct version. Not really sure if this is enough of a problem to actually define the version in code.

**Comment by kkga** [comment]
I didn't pull the master btw, this is built from the latest tagged release: https://github.com/kraxarn/spotify-qt/archive/v3.1.tar.gz

**Comment by kraxarn** [comment]
Currently it works like that as I don't trust myself to remember to update the version in the file before releasing a new version :joy:. I'll definitely consider keeping the version in a file though to make it easier for package maintainers and stuff.

**Comment by kraxarn** [comment]
Thought a bit about this, and I think it's nice to be able to distinguish versions built from master and "stable builds", so I decided to define it in code, and instead fetch the git commit the application was built from, and show it as a "development build".

Also noticed I couldn't seem to find version definitions in packages maintained by others, so I doubt they fetch the correct version either, so this is probably for the best. Feel free to keep me updated if you ever get the package on Void Linux so I can add it to the list in the readme :relaxed:
