### ISSUE TITLE
Could not find or load the Qt platform plugin "wayland-egl" when installed as snap

### ISSUE THREAD

**Issue by varac** [kraxarn/spotify-qt#35]
### System information

* application version: v3.1
* current desktop environment: wayland (sway)
* operating system and version: Ubuntu 20.10
* as well as Qt version: Doesn't apply since I installed spotify-qt as snap container

### Detailed information

```
❯ spotify-qt 
This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Reinstalling the application may fix this problem.
[1]    33359 abort (core dumped)  spotify-qt
```

### What happens?

I try to start `spotify-qt` but it crashes.

### What should happen?

It shouldn't crash and it should support wayland out of the box when installed as snap.

**Comment by kraxarn** [comment]
New version released to the edge channel with Wayland support, please try it out :relaxed:

**Comment by varac** [comment]
Doesn't work:

```
$ sudo snap install --channel=edge spotify-qt
spotify-qt (edge) v3.1 aus Kraxie (kraxarn) installiert

$ /snap/bin/spotify-qt
Failed to create display (Permission denied)
```

I don't know how to increase verbosity here, since there seems be be not help command ?

```
$ /snap/bin/spotify-qt --help
Failed to create display (Permission denied)

```

Btw, there are two different snaps uploaded with the same version number, please update the version so users can identify the difference:

```
$ snap info spotify-qt 
...
channels:
  latest/stable:    v3.1 2020-11-08  (69) 110MB -
  latest/candidate: ↑                           
  latest/beta:      ↑                           
  latest/edge:      v3.1 2020-11-19 (148) 113MB -
installed:          v3.1            (148) 113MB -
```

**Comment by kraxarn** [comment]
Seems like Wayland support with snaps is [really poor](https://forum.snapcraft.io/t/problem-launching-qt-snaps-in-wayland/7055) and just getting it to run seems to currently be a pain. It also doesn't use system theming, so it also doesn't look right.

For now, I just added `DISABLE_WAYLAND=1`, which seems to make it launch under Wayland at least. For proper Wayland support, I would suggest getting it from a package manager or just compile from source, as that seems to work much better.
