### ISSUE TITLE
snap package D-Bus not plugged - MPRIS not working

### ISSUE THREAD

**Issue by akrus** [kraxarn/spotify-qt#38]
Currently snap package has the following plugs enabled:
```
plugs: [home, opengl, network, network-bind, unity7]
```

As D-Bus interface is not in the list, MPRIS doesn't work and the app complains when starting.
Workaround is to use --devmode, although adding dbus to the list of plugs would be a better option.

**Comment by J-Cake** [comment]
thanks for workaround

**Comment by kraxarn** [comment]
Was unable to reproduce the issue as it worked fine for me, maybe already included in the unity7 interface? Added an explicit plug for dbus either way.
