### ISSUE TITLE
Feature request: Play song from any list by pressing a key

### ISSUE THREAD

**Issue by uninhm** [kraxarn/spotify-qt#40]
It can be space or enter, for example.

**Comment by uninhm** [comment]
Maybe with QTreeWidget::itemActivated

**Comment by uninhm** [comment]
See this:

https://github.com/uninhm/spotify-qt/commit/bfd31b8db946b7653e82dd7a459b907998c1a3ff

**Comment by kraxarn** [comment]
Looks better than even having a setting for changing between single/double click, can you make a pull request?

**Comment by uninhm** [comment]
> can you make a pull request?
Sure!
