### ISSUE TITLE
Dark theme bug

### ISSUE THREAD

**Issue by uninhm** [kraxarn/spotify-qt#42]
[This commit](https://github.com/kraxarn/spotify-qt/commit/d35555ba2e10de496d765376be877dcfc736ad6c) has the following bug:

![image](https://user-images.githubusercontent.com/62044675/103042034-f384c200-4556-11eb-84fc-1cee75205a37.png)

**Comment by kraxarn** [comment]
It's in the master branch and untested :p Should be fixed in 7034483ada01518aa1478a42fb3666bcfd99ede1 though.

**Comment by uninhm** [comment]
> It's in the master branch and untested :p

So it should be a 'untested' branch for that. I though 'master' branch was with working code :P

I can open a issue for that if you want :stuck_out_tongue_closed_eyes:

**Comment by uninhm** [comment]
> Should be fixed in [7034483](https://github.com/kraxarn/spotify-qt/commit/7034483ada01518aa1478a42fb3666bcfd99ede1) though.

It miss menus, buttons mouse-over-highlight, checkbuttons, line-edits, comboboxes...

**Comment by uninhm** [comment]
You can set an 'stable' branch as default:

https://github.com/uninhm/spotify-qt

**Comment by kraxarn** [comment]
I'll test it some more when I get the time to.
I know how branches work, it's just how it's set up currently :p

**Comment by uninhm** [comment]
@kraxarn tracks info is unreadable when selected

**Comment by uninhm** [comment]
Fixed, see #47

**Comment by uninhm** [comment]
I think that's the last bug, so the PR closes this issue.

**Comment by uninhm** [comment]
Whaaaat, why isn't this closed? Are there still bugs about this?

**Comment by kraxarn** [comment]
The only bug I'm currently aware of is that system icons doesn't work well with the custom dark theme. Workaround being that built-in icons are automatically enabled when using the custom dark theme.
I mostly forgot about this issue, but I guess it's safe to close now :relaxed:
