### ISSUE TITLE
Player command failed: Premium required

### ISSUE THREAD

**Issue by qerqeq** [kraxarn/spotify-qt#48]
Upon attempting to make any action within the client, this error shows up at the bottom left of the interface. For example, when trying to play any song it states:
Failed to start playback: Player command failed: Premium required

edit: I can supply any information upon request.

**Comment by qerqeq** [comment]
I thought this was an error, I realized only now that you need premium! Silly me.

**Comment by TheShubhendra** [comment]
i just bought premium and premium feature is working well in my phone, but in spotify-qt I am still getting this error.
