### ISSUE TITLE
[Question/Feature] Can't zoom in?

### ISSUE THREAD

**Issue by sunchaesk** [kraxarn/spotify-qt#51]
Hello, just tried out spotify-qt which I really enjoyed but I was wondering how I can zoom in, or if that feature is not support at all. For smaller screens like the one I have, I can hardly read the text.

**Comment by kraxarn** [comment]
What version of Qt, and operating system, are you using? Does other Qt applications have a similar issue? Did you try using`QT_AUTO_SCREEN_SCALE_FACTOR`? Currently, the application doesn't have any explicit high dpi support, but it might change if there are issues with it.

**Comment by sunchaesk** [comment]
I'm using artix linux (basically arch), but I haven't used any QT applications in a long time, and am not expert in the foss applications only around intermediate, so not sure what QT_AUTU_SCREEN_SCALE_FACTOR is... I'm assuming it is part of config?

I tried downloading some other QT applications for testing, and I was able to zoom in, but using zoom in buttons that comes with it...

**Comment by kraxarn** [comment]
You use it as an [environment variable](https://wiki.archlinux.org/index.php/Environment_variables), so you can, for example, start the application using `QT_AUTO_SCREEN_SCALE_FACTOR=1 spotify-qt` and see if it works better. I also committed a proper patch, so you can try building from source as well.

**Comment by sunchaesk** [comment]
It's working better thanks
