### ISSUE TITLE
Search sidebar suggestions

### ISSUE THREAD

**Issue by lf-** [kraxarn/spotify-qt#53]
I have really enjoyed the performance and simplicity of spotify-qt, but there are a few usability issues with the search box that often have me switching to the web client (checked on gc402a01):

I have trouble reading things in the results list as it is not wide enough so it truncates things. It seems to not be possible to make bigger as dragging the boundary on it seems to not change its width. I'd also like to see album names as an optional column in the tracks list as it is hard to distinguish between songs both released as singles and as part of albums.

This image shows both of these: 

![image](https://user-images.githubusercontent.com/6652840/106525694-3ceef800-6499-11eb-8abd-80097f9bbb29.png)

**Comment by kraxarn** [comment]
All sidebars should be able to be resized, i agree, and definitely something that will be changed soon. If it would be resized wider, additional information could also easily fit.

**Comment by BlueDrink9** [comment]
Another note: clicking the search button when opening this sidebar should auto-focus the search box. For me, it does not
