### ISSUE TITLE
Not all "Liked Albums" listed

### ISSUE THREAD

**Issue by gjgress** [kraxarn/spotify-qt#59]
The list of "Liked Albums" in the spotify-qt client seems to be a small portion of the actual list... Not sure where to look to begin figuring out the issue.

![Screenshot from 2021-02-21 22-24-21](https://user-images.githubusercontent.com/34071465/108662391-d5bed500-7493-11eb-8e45-f5f97c1f2161.png)

**Comment by kraxarn** [comment]
Quite simple actually. For some reason, when loading the liked albums, it only loads the first 10 results:
https://github.com/kraxarn/spotify-qt/blob/9b812dbdd91da535f42eac76c33611232e834f87/src/spotify/spotify.cpp#L535
Not sure why I made it that way, guess to not fill the list too much, but definitely an issue.

**Comment by gjgress** [comment]
Hooray for simple fixes!

**Comment by kraxarn** [comment]
I hope this was fixed in e867e70ee0c11f1156e4c644b97c7c12a74625d7.
