### ISSUE TITLE
new feature - list filter

### ISSUE THREAD

**Issue by arosiek** [kraxarn/spotify-qt#60]
I would love to have the list filter in the desktop app

**Describe the solution:**
I have quite big "Liked Tracks" list. sometimes I would like to find my favorite track fast or just filter via artist. I'm missing it in spotify app as well. I would love to have this kind of filter on the list.

**Comment by kraxarn** [comment]
Similar to #50, and I think the best way to solve it is to just add another tab to the search view for searching your library.
