### ISSUE TITLE
New feature - Clicking progress bar

### ISSUE THREAD

**Issue by jeppevinkel** [kraxarn/spotify-qt#62]
Coming from almost any other music player, I expect to be able to click the song progress bar to go to a point in the song.  
In this player I have to drag the circle on the progress bar directly to move it, which is counter intuitive compared to most common players.

Everything else about the player is really nice, and I'm currently trying it out to be my new main player.

**Comment by kraxarn** [comment]
It depends on what style you are using, some allow it, and some don't. As the default Qt style, Fusion, doesn't allow it, manually adding it is probably a good idea.
