### ISSUE TITLE
Connection failure on boot

### ISSUE THREAD

**Issue by Asheboy** [kraxarn/spotify-qt#64]
### System information
![image](https://user-images.githubusercontent.com/1822529/108911249-ee0f2b00-761e-11eb-83fe-d79ab0320375.png)
Spotify-qt Version: v3.3

### Detailed information
When opening the application, I received the following:
![image](https://user-images.githubusercontent.com/1822529/108911330-0aab6300-761f-11eb-9664-53ad7e2b8a02.png)

**Comment by kraxarn** [comment]
The `Refresh token revoked` error sounds like you have used it before, but you changed your password or similar to make the login invalid? I have plans to improve this, but could you try launching it with `--reset-credentials`?

**Comment by Asheboy** [comment]
Ah, that'll be it! As soon as I created and used the token, Spotify reset my password because of 'unusual activity'. `--reset-credentials` did the trick - thank you!
