### ISSUE TITLE
Failed to apply setting "spotifyd path"

### ISSUE THREAD

**Issue by Asheboy** [kraxarn/spotify-qt#65]
### System information
![image](https://user-images.githubusercontent.com/1822529/108911249-ee0f2b00-761e-11eb-83fe-d79ab0320375.png)
Spotify-qt Version: v3.3

### Detailed information
Get the following when trying to “Apply” the Spotify settings.
![image](https://user-images.githubusercontent.com/1822529/108914602-83142300-7623-11eb-910c-aeecf55e53a2.png)

**Comment by kraxarn** [comment]
Are you using the snap version? Some people are having issues using the Spotify client functionality from the snap. I think it's a security thing by the snap container thing though, and nothing I can really do about, but I'm also very inexperienced with snaps in general. The snap version is also not currently updated to v3.4.

The Spotify client functionality does suck though, and is often very buggy. I just don't want to focus on it too much, but instead just add playback functionality directly in the client instead. For now, starting the client externally is recommended when exeperiencing issues.

**Comment by Asheboy** [comment]
Yes, snap version. Thanks for the workaround.

**Comment by Schatteneis** [comment]
this happens on self compiled and appimage version too

**Comment by Schatteneis** [comment]
editing the path manually in the config.json worked

**Comment by kraxarn** [comment]
Are you using librespot or spotifyd? Which version are you using? Just tried with both librespot and spotifyd, and seems to work fine. Either way, I have now improved the error handling to hopefully show a more useful error message, so I'm closing this.
