### ISSUE TITLE
Feature Request: Ability to play on mutiple devices at once

### ISSUE THREAD

**Issue by pghpete** [kraxarn/spotify-qt#69]
Not sure if this is possible but it would be great if you could tick/check more than one device to play the audio on multiple devices in various rooms in your home. I have several raspotify nodes and several spotifyd nodes.  If this is something that may one day be possible and I can help out in any way debug/compile/document etc, please let me know.

Thanks!

**Comment by kraxarn** [comment]
When selecting a device to play to from the API, you actually need to send in an array of devices, although, only one device is currently supported, but that means that this could be something they consider changing in the future.

One way to "get around it" would be to have one primary device that streams the music from Spotify, and then some secondary devices that streams from the primary device. I believe this is how some speaker systems do it.

**Comment by kraxarn** [comment]
Closing as this isn't officially supported and outside the scope of this project.
