### ISSUE TITLE
Album track

### ISSUE THREAD

**Issue by Dulkien** [kraxarn/spotify-qt#7]
just the first 50 music in a album

![Capture d’écran_2020-04-12_19-58-54](https://user-images.githubusercontent.com/39432426/79076268-13da5c80-7cf9-11ea-908a-e19de7f5c443.png)

**Comment by kraxarn** [comment]
Album tracks do not currently have any pagination as i didn't expect an album to have that many tracks.

**Comment by Dulkien** [comment]
I think the album track are stored (by default) with the number of the track. And yes, game OST have a lot of music ! 😅
