### ISSUE TITLE
Give password permanently?

### ISSUE THREAD

**Issue by katakombi** [kraxarn/spotify-qt#70]
Great app, thanks a lot for this!
But would there be a way to add the password for spotifyd permanently as I don't want to copynpaste it every time?

**Comment by kraxarn** [comment]
Currently, only KWallet is supported for password storage, but as this is designed to be portable, I think some simple password encryption could be useful.

**Comment by Deuchnord** [comment]
You actually can store securely your password with solution presented in [`spotifyd`'s docs](https://spotifyd.github.io/spotifyd/config/File.html):
1. Create or edit the file at `~/.config/spotifyd/spotifyd.conf`:
   ```
   [global]
   username = "your@email.com"
   use_keyring = true
   ```
2. Invoke the following command:
   ```bash
   secret-tool store --label='name you choose' application rust-keyring service spotifyd username <your-username>
   ```
   You will be prompted for your password.

Once it is done, give `spotifyd` a try with `spotifyd --no-daemon`: if it returns `Authenticated as "[some random-like string]" !` in the standard output, then it is ready.

The last think you need to do is to activate _Use global config_ in Spotify-Qt's options.
Restart, and see the magic happen 🪄

**Comment by kraxarn** [comment]
`spotify-qt` prefers using CLI arguments over configuration files. If you want to configure it that way, I would recommend setting everything in your config file, and enabling "use global config" in the app. I didn't know about `secret-tool` though, might be interesting for support outside of KDE.

**Comment by lbiaggi** [comment]
> You actually can store securely your password with solution presented in [`spotifyd`'s docs](https://spotifyd.github.io/spotifyd/config/File.html):
> 
>     1. Create or edit the file at `~/.config/spotifyd/spotifyd.conf`:
>        ```
>        [global]
>        username = "your@email.com"
>        use_keyring = true
>        ```
> 
>     2. Invoke the following command:
>        ```shell
>        secret-tool store --label='name you choose' application rust-keyring service spotifyd username <your-username>
>        ```
>        
>        
>        You will be prompted for your password.
> 
> 
> Once it is done, give `spotifyd` a try with `spotifyd --no-daemon`: if it returns `Authenticated as "[some random-like string]" !` in the standard output, then it is ready.
> 
> The last think you need to do is to activate _Use global config_ in Spotify-Qt's options.
> Restart, and see the magic happen 🪄

`spotifyd.conf`
[global]
username = "mail"
use_keyring = true


`keepassxc`
expose the pass with [Secret Service](https://avaldes.co/2020/01/28/secret-service-keepassxc.html)

maybe spotify-qt could support the Secret Service directly?

**Comment by kraxarn** [comment]
KWallet does implement the secret service, so switching wouldn't affect current users. It's just something that's planned, but I haven't actually gotten around to implementing yet.

**Comment by IlyaBizyaev** [comment]
Is this feature somewhat hidden at the moment? It looks like `USE_KEYCHAIN` needs to be set somewhere, but it's not listed in CMakeLists.txt. According to the Troubleshooting page, it's off in openSUSE.

**Comment by kraxarn** [comment]
It's "ON" by default in "lib/thirdparty/CMakeLists.txt".
I don't build or maintain the openSUSE package, so I don't know if it's manually disabled there or why it would be.

**Comment by IlyaBizyaev** [comment]
I don't see it being disabled:
https://build.opensuse.org/package/view_file/multimedia:apps/spotify-qt/spotify-qt.spec?expand=1

But does setting it in https://github.com/kraxarn/spotify-qt/blob/master/lib/thirdparty/CMakeLists.txt make it visible to source files in other subdirectories?

**Comment by kraxarn** [comment]
Yes, but it disabled itself automatically if libsecret cannot be found, instead of failing to build, so maybe that's why.
