### ISSUE TITLE
Close to systemtray

### ISSUE THREAD

**Issue by katakombi** [kraxarn/spotify-qt#71]
And yet another feature wish...
To close the app window to the systray instead of terminating the app. I could give it a try myself and do a pull request...
Just tell me if that is OK as a feature for the main app.

**Comment by kraxarn** [comment]
You can click the tray icon itself to hide and show the main window. Feel free to do a pull request if you want to though, or I'll take a look at it for the next release ^^

**Comment by kraxarn** [comment]
This was fixed in #151 (v3.9).
