### ISSUE TITLE
Set default device

### ISSUE THREAD

**Issue by drumfreakk** [kraxarn/spotify-qt#73]
Currently when you're playing on a different device and its paused for a while, it disconnects and when you want to resume playback you have to select the device you want to play it on manually, and I think it would be useful to be able to select a default device to play on in this type of scenario.

**Comment by kraxarn** [comment]
If only one device is available, it should be automatically selected when playing a track, so I guess that's why I don't think it's a huge issue, but definitively something to look into :relaxed:

**Comment by kippenjongen** [comment]
Ok, that makes sense, but thanks for looking in to it!
