### ISSUE TITLE
Feature request: make side bar width adjustable

### ISSUE THREAD

**Issue by ZweiEuro** [kraxarn/spotify-qt#74]
When e.g. searching something, the side bar has the search results, but most of the time the results are cut off by artist or by the end of the screen, while to the left is loads of unused space
![2021-03-05-42](https://user-images.githubusercontent.com/18036573/110156050-c53d2180-7de6-11eb-8b46-a101e9b08dad.png)

Could It be made possible to make to edge between the right most and middle window on the right side shift-able to the left (permanently)?

**Comment by kraxarn** [comment]
Similar to #53, but yes, definitively something I will change very soon.

**Comment by kraxarn** [comment]
This was fixed mostly in d236b1a0e1b8fa4030bc163dd033a54571a5d135.
