### ISSUE TITLE
Like button doesn't unlike

### ISSUE THREAD

**Issue by drumfreakk** [kraxarn/spotify-qt#75]
When you left-click on a track it gives the option to like a track, which it successfully does, but when you left-click an already liked track, it doesn't give any indication that it's already been liked and when you click it it also doesn't unlike it, so I'd suggest making the star become solid have it unlike the track once it is already liked.

**Comment by kippenjongen** [comment]
Like the follow/unfollow button that artists have already actually

**Comment by kraxarn** [comment]
Currently it only checks if the track is in the cache, so you have to open liked tracks from your library first for it to properly update, but a similar check as the one in the artist view would be much better.
