### ISSUE TITLE
Incorrect Instrumentalness value in Audio Features

### ISSUE THREAD

**Issue by m3tav3rse** [kraxarn/spotify-qt#82]
### System information

Not relevant
### Detailed information

Currently `values["Instrumentalness"]` in [src/spotify/audiofeatures.cpp](https://github.com/kraxarn/spotify-qt/blob/a419b152480ed894045adedf8490d9bb1570b421/src/spotify/audiofeatures.cpp#L13) is displayed as: 0 instrumental - ... - 1 not instrumental.
Should be: 1 Instrumental - ... - 0 not instrumental.
Spotify API for reference: https://developer.spotify.com/documentation/web-api/reference/#object-audiofeaturesobject
### What happens?

Right click any song -> Audio features -> Look at Instrumentalness
### What should happen?

Instrumantalness value should be displayed properly.

**Comment by m3tav3rse** [comment]
I will be happy to provide PR on this if possible.

**Comment by kraxarn** [comment]
You are very welcome to, it's just that this view really needs to be reworked, as most of the values doesn't really make any sense, or are just inaccurate.
