### ISSUE TITLE
Added spotify-qt to nixpkgs

### ISSUE THREAD

**Issue by karthikiyengar** [kraxarn/spotify-qt#88]
Thanks for the package. I've added it to nixpkgs, and it's currently in the unstable channel [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/audio/spotify-qt/default.nix). You might want to list this on the Readme.

**Comment by kraxarn** [comment]
Thank you! Badge doesn't seem to work yet, but added it anyway.
