### ISSUE TITLE
No icon in the app menu on Ubuntu/Gnome

### ISSUE THREAD

**Issue by Matipolit** [kraxarn/spotify-qt#89]
### System information
ABI: x86_64-little_endian-lp64
App version: v3.5-dev (eb104e0)
Current desktop: ubuntu:GNOME
D-Bus support: Yes
Device: mateusz_desktop_spotifyd (Computer)
Kernel: linux 5.8.0-48-generic
Product: Ubuntu Core 18
Qt version: 5.9.5

### Detailed information
There is no clickable icon for spotify-qt in the Gnome app menu, at least in the Snap store version.

**Comment by kraxarn** [comment]
It's a feature coming up in the next version, see #80 :relaxed:
