### ISSUE TITLE
Status bar VS desktop notifications

### ISSUE THREAD

**Issue by joaopauloalbq** [kraxarn/spotify-qt#9]
I think the status bar could easily be replaced for desktop notifications.

**Pros:**

- Better use of space
- Minimalist

**Comment by kraxarn** [comment]
What do you mean by "desktop notifications"? It currently has basic media player support, but it needs to be improved.

**Comment by joaopauloalbq** [comment]
I'm talking about remove the status bar (in red) and send the "status" of it by notifications, as in the second figure.

![status_bar](https://user-images.githubusercontent.com/9905202/79801673-e57e0200-8334-11ea-8842-1cfaf54623c9.png)

![notification](https://user-images.githubusercontent.com/9905202/79802034-a2705e80-8335-11ea-83c1-a0ecb2ad8b7a.png)

You got it? My English isn't really good...

**Comment by kraxarn** [comment]
Then I understand what you mean. I just thought a status bar would make more sense, as it only shows notifications while you are using the application itself. I will consider adding an option to use desktop notifications instead.

**Comment by joaopauloalbq** [comment]
My point is that it is almost never used and most of the time it is blank, it seems strange in the application, like a title bar without title, in addition to the waste of space.
Thank you for considering an option.
