### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by toylatte** [kraxarn/spotify-qt#90]
### System information
MacOS 10.15.7
Error log: https://gist.github.com/toylatte/7061bb9c125d620e328259acd2910ef2

### Detailed information
After running ./spotify-qt, it says `[info] Last refresh was less than an hour ago, not refreshing access token` and `18556 segmentation fault  ./spotify-qt`

**Comment by kraxarn** [comment]
Thanks for the log, looks like there's an issue with getting the last opened playlist. As a workaround, you could try manually setting any value, like just a single letter, in `General.last_playlist` from your config file and see if that works better.

**Comment by toylatte** [comment]
Are you talking about `spotify-qt/lib/src/settings.cpp`? I tried changing lines 37 and 127 to include `"a"` instead of `general.last_playlist`. Still a segmentation fault error. 
This is my new error log: [https://gist.github.com/toylatte/cfc5ce65f4307602e166ab4d3ab30816](https://gist.github.com/toylatte/cfc5ce65f4307602e166ab4d3ab30816), which looks like it has the same issue. The parent process field has changged from spotify-qt to zsh.

**Comment by kraxarn** [comment]
Nah, in the application settings file, which should be in something like 	"~/Library/Preferences/kraxarn/spotify-qt.json", i don't have a mac on me right now to verify. I did try removing the value on my machine though and got a similar crash, so it's most likely that.

**Comment by toylatte** [comment]
Works now. Thanks!

**Comment by kraxarn** [comment]
It was mostly meant as a temporary workaround and to see what was the actual issue. A proper fix has now been implemented :relaxed:
