### ISSUE TITLE
Shuffle doesn't work when switching playlists

### ISSUE THREAD

**Issue by canisli** [kraxarn/spotify-qt#92]
### System information
MacOS 10.15.7

### What happens?
After you switch to a different playlist, you have to turn off shuffle and then turn it back on for the playlist songs to shuffle.

**Comment by kraxarn** [comment]
Are you using librespot or spotifyd? I noticed this as well, but it seems to work fine when using the official client, so i think the actual bug is in librespot. A simple workaround to automatically toggle it within the application could easily be added though until it's fixed.

**Comment by canisli** [comment]
I'm using spotifyd. I just tried the official client and it works like you said.

**Comment by kraxarn** [comment]
Closing as it's not an issue with spotify-qt.
