### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by kraxarn** [kraxarn/spotify-qt#95]
* [ ] Builds are unsigned, which can cause a SmartScreen warning and false positives from some anti-virus applications.
* [x] Built using MinGW, which removes the need to install any Visual C++ runtime, but adds ~45 MB to the installation.
* [x] Is not available from any package manager, and has no automatic updates (add to winget).

**Comment by brian6932** [comment]
> - [x] Is not available from any package manager, and has no automatic updates (add to winget).

I have made a scoop package for this, it is on my personal bucket though, if you'd like I could PR to a larger bucket like extras to make it easier to get

**Comment by kraxarn** [comment]
To my understanding, there are 2 major package managers for Windows, one being scoop and one being Chocolatey. I read a bit about the differences, and to my understanding, scoop is more for developer CLI tools, while Chocolatey is more for general applications. For example, the documentation mentions that "Scoop focuses on open-source, command-line developer tools". It might be different for the extras bucket, and if you think it would fit there, you are very welcome to add it there. I'm not very experienced with Windows development in general, but to me, it sounds like Chocolatey would be a better fit.

**Comment by brian6932** [comment]
@kraxarn 
They are both usable, scoop has buckets in which the maintainers can set different requirements, what you're referring to as:
>developer CLI tools

is a requirement for the main bucket.
Scoop is very decentralized, there are many other buckets, and anyone can open and make manifests in their bucket, I made one for spotify-qt [here](https://github.com/brian6932/dank-scoop/blob/master/bucket/spotify-qt.json).

This is a personal bucket ofc, so you won't really find it, or use it, unless you have the bucket added. You can specify it's install process somewhere, or use a scoop indexer like [this one](https://github.com/zhoujin7/scoop-search).

Now for major buckets, if a manifest is not fit for the main bucket (which is the default indexed scoop bucket), it can go into the extras bucket. Either way a manifest has been made, so it can be documented to either my personal bucket, or I can PR it to extras and you can have that documented. For example I recently made a manifest and had it documented [here](https://github.com/TheZoraiz/ascii-image-converter#scoop),

I personally use both choco and scoop, although I will say it is a good bit easier to write and maintain auto updating scoop manifests as opposed to choco packages, especially on GitHub.

**Comment by brian6932** [comment]
[I have also made an auto updating nightly manifest as well](https://github.com/brian6932/dank-scoop/blob/master/bucket/spotify-qt-nightly.json)

**Comment by kraxarn** [comment]
Just tried it myself, and seems to work fine, but I can't get it to properly update. I'm not sure if I'm just doing something wrong, but I've tried both `scoop update` and `scoop install`, and both just always tell me the latest version is already installed.

**Comment by brian6932** [comment]
@kraxarn `scoop update *`

**Comment by brian6932** [comment]
If the version is out of date, it will update it

**Comment by kraxarn** [comment]
Ah, I was missing the `*`, seems to work now, thanks. Will see later if I decide to publish it anywhere else myself, but this will work perfectly fine for the time being.

**Comment by kraxarn** [comment]
Testing this more, sometimes it works, but sometimes it doesn't. For example, I can get an output like this:

```
PS> scoop update
Updating Scoop...
Updating 'dank-scoop' bucket...
 * f3e85fc spotify-qt-nightly: Update to version 3.8-4b12309
Updating 'main' bucket...
Scoop was updated successfully!

PS> scoop update spotify-qt-nightly
spotify-qt-nightly: 3.8-f7a62ec (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

Where there is a newer/other version available, but it doesn't want to update, as it considers the installed version newer. I'm not sure if it has anything to do with using hashes for versioning, but I renamed the files to follow the current date instead, as I think it makes more sense for nightly versions anyway.

**Comment by brian6932** [comment]
Yea sometimes nightly packages have some issues, if you want to force an update with scoop, you can do:
`scoop update spotify-qt-nightly -f`

**Comment by brian6932** [comment]
@kraxarn Oh nevermind lol, I should've checked when the last update was before sending that last message. It just takes a few hrs for the automatic excavator update checker to batch check all the packages in the repo and update it, I'll force the updater to update it since you noticed 👍

**Comment by brian6932** [comment]
@kraxarn Update, the PRs I made to [ScoopInstaller/Extras](https://github.com/ScoopInstaller/Extras/blob/master/bucket/spotify-qt.json) and [ScoopInstaller/Versions](https://github.com/ScoopInstaller/Versions/blob/master/bucket/spotify-qt-nightly.json) for `spotify-qt` and `spotify-qt-nightly` have been merged, so they are now official manifests.

[Thus I will be deleting them from my personal repo](https://github.com/brian6932/dank-scoop/pull/13), instructions on how to get them from now on:
```
scoop uninstall spotify-qt spotify-qt-nightly
scoop bucket add extras
scoop bucket add versions
scoop update
```
After this has been ran, you can install the packages normally:
```
scoop install spotify-qt-nightly
```
**OR**
```
scoop install spotify-qt
```

**Comment by kraxarn** [comment]
Closing as this is more or less resolved now. It's still unsigned, but it's not enough of an issue to fix right now.
